# This file is intended to be shared between the Archipelago Client/World and the Game sdkmod.
# I don't expect to be able to have one source of truth distributed to both, so just keep the two files in sync.

level_name_to_id = {
    # 2 through 30
    "Level " + str(i) : i for i in range(2, 31)
}

gear_kind_to_id = {
    # Gear
    "Common Shield":                    100,
    "Uncommon Shield":                  101,
    "Rare Shield":                      102,
    "VeryRare Shield":                  103,
    # "E-Tech Shield":                    104,
    "Legendary Shield":                 105,
    # "Seraph Shield":                    106,
    # "Rainbow Shield":                   107,
    # "Pearlescent Shield":               108,
    # "Unique Shield":                    109,

    "Common GrenadeMod":                110,
    "Uncommon GrenadeMod":              111,
    "Rare GrenadeMod":                  112,
    "VeryRare GrenadeMod":              113,
    # "E-Tech GrenadeMod":                114,
    "Legendary GrenadeMod":             115,
    # "Seraph GrenadeMod":                116,
    # "Rainbow GrenadeMod":               117,
    # "Pearlescent GrenadeMod":           118,
    # "Unique GrenadeMod":                119,

    "Common ClassMod":                  120,
    "Uncommon ClassMod":                121,
    "Rare ClassMod":                    122,
    "VeryRare ClassMod":                123,
    # "E-Tech ClassMod":                  124,
    "Legendary ClassMod":               125,
    # "Seraph ClassMod":                  126,
    # "Rainbow ClassMod":                 127,
    # "Pearlescent ClassMod":             128,
    # "Unique ClassMod":                  129,

    "Common Relic":                     130,
    "Uncommon Relic":                   131,
    "Rare Relic":                       132,
    "VeryRare Relic":                   133,
    # "E-Tech Relic":                     134,
    # "Legendary Relic":                  135,
    # "Seraph Relic":                     136,
    # "Rainbow Relic":                    137,
    # "Pearlescent Relic":                138,
    # "Unique Relic":                     139,

    "Common Pistol":                    140,
    "Uncommon Pistol":                  141,
    "Rare Pistol":                      142,
    "VeryRare Pistol":                  143,
    "E-Tech Pistol":                    144,
    "Legendary Pistol":                 145,
    # "Seraph Pistol":                    146,
    # "Rainbow Pistol":                   147,
    # "Pearlescent Pistol":               148,
    "Unique Pistol":                    149,

    "Common Shotgun":                   150,
    "Uncommon Shotgun":                 151,
    "Rare Shotgun":                     152,
    "VeryRare Shotgun":                 153,
    "E-Tech Shotgun":                   154,
    "Legendary Shotgun":                155,
    # "Seraph Shotgun":                   156,
    # "Rainbow Shotgun":                  157,
    # "Pearlescent Shotgun":              158,
    "Unique Shotgun":                   159,

    "Common SMG":                       160,
    "Uncommon SMG":                     161,
    "Rare SMG":                         162,
    "VeryRare SMG":                     163,
    "E-Tech SMG":                       164,
    "Legendary SMG":                    165,
    # "Seraph SMG":                       166,
    # "Rainbow SMG":                      167,
    # "Pearlescent SMG":                  168,
    "Unique SMG":                       169,

    "Common SniperRifle":               170,
    "Uncommon SniperRifle":             171,
    "Rare SniperRifle":                 172,
    "VeryRare SniperRifle":             173,
    "E-Tech SniperRifle":               174,
    "Legendary SniperRifle":            175,
    # "Seraph SniperRifle":               176,
    # "Rainbow SniperRifle":              177,
    # "Pearlescent SniperRifle":          178,
    "Unique SniperRifle":               179,

    "Common AssaultRifle":              180,
    "Uncommon AssaultRifle":            181,
    "Rare AssaultRifle":                182,
    "VeryRare AssaultRifle":            183,
    "E-Tech AssaultRifle":              184,
    "Legendary AssaultRifle":           185,
    # "Seraph AssaultRifle":              186,
    # "Rainbow AssaultRifle":             187,
    # "Pearlescent AssaultRifle":         188,
    "Unique AssaultRifle":              189,

    "Common RocketLauncher":            190,
    "Uncommon RocketLauncher":          191,
    "Rare RocketLauncher":              192,
    "VeryRare RocketLauncher":          193,
    "E-Tech RocketLauncher":            194,
    "Legendary RocketLauncher":         195,
    # "Seraph RocketLauncher":            196,
    # "Rainbow RocketLauncher":           197,
    # "Pearlescent RocketLauncher":       198,
    "Unique RocketLauncher":            199,
}

quest_name_to_id = {
    "The Road to Sanctuary":                                  200,
    "Plan B":                                                 201,
    "Hunting the Firehawk":                                   202,
    "A Train to Catch":                                       203,
    "Rising Action":                                          204,
    "Bright Lights, Flying City":                             205,
    "Data Mining":                                            206,
    "Breaking the Bank":                                      207,
    "Kill Yourself":                                          208,
    "This Just In":                                           209,
    "My First Gun":                                           210,
    "Clan War: Wakey Wakey":                                  211,
    "Handsome Jack Here!":                                    212,
    "This Town Ain't Big Enough":                             213,
    "Shielded Favors":                                        214,
    "Symbiosis":                                              215,
    "Defend Slab Tower":                                      216,
    "Best Mother's Day Ever":                                 217,
    "Note for Self-Person":                                   218,
    "The Bane":                                               219,
    "The Good, the Bad, and the Mordecai":                    220,
    "The Lost Treasure":                                      221,
    "Arms Dealing":                                           222,
    "3:10 to Kaboom":                                         223,
    "Customer Service":                                       224,
    "Neither Rain nor Sleet nor Skags":                       225,
    "Blindsided":                                             226,
    "Cleaning up the Berg":                                   227,
    "Best Minion Ever":                                       228,
    "A Dam Fine Rescue":                                      229,
    "Wildlife Preservation":                                  230,
    "The Once and Future Slab":                               231,
    "The Man Who Would Be Jack":                              232,
    "Where Angels Fear to Tread":                             233,
    "Where Angels Fear to Tread (Part 2)":                    234,
    "Toil and Trouble":                                       235,
    "The Talon of God":                                       236,
    "Assassinate the Assassins":                              237,
    "Bad Hair Day":                                           238,
    "Bearer of Bad News":                                     239,
    "BFFs":                                                   240,
    "Cult Following: Eternal Flame":                          241,
    "Cult Following: Lighting the Match":                     242,
    "Cult Following: The Enkindling":                         243,
    "Claptrap's Secret Stash":                                244,
    "You Are Cordially Invited: Party Prep":                  245,
    "The Ice Man Cometh":                                     246,
    "In Memoriam":                                            247,
    "Mighty Morphin'":                                        248,
    "Mine, All Mine":                                         249,
    "Minecart Mischief":                                      250,
    "The Name Game":                                          251,
    "No Hard Feelings":                                       252,
    "No Vacancy":                                             253,
    "Perfectly Peaceful":                                     254,
    "Rock, Paper, Genocide: Slag Weapons!":                   255,
    "Rock, Paper, Genocide: Fire Weapons!":                   256,
    "Do No Harm":                                             257,
    "The Pretty Good Train Robbery":                          258,
    "Won't Get Fooled Again":                                 259,
    "A Real Boy: Face Time":                                  260,
    "A Real Boy: Clothes Make the Man":                       261,
    "Claptrap's Birthday Bash!":                              262,
    "Clan War: Zafords vs. Hodunks":                          263,
    "Animal Rights":                                          264,
    "Hell Hath No Fury":                                      265,
    "Home Movies":                                            266,
    "Statuesque":                                             267,
    "Showdown":                                               268,
    "Clan War: End of the Rainbow":                           269,
    "Clan War: Starting the War":                             270,
    "The Overlooked: Medicine Man":                           271,
    "The Overlooked: Shields Up":                             272,
    "The Overlooked: This Is Only a Test":                    273,
    "Poetic License":                                         274,
    "Clan War: First Place":                                  275,
    "Safe and Sound":                                         276,
    "Animal Rescue: Shelter":                                 277,
    "Slap-Happy":                                             278,
    "Stalker of Stalkers":                                    279,
    "You. Will. Die. (Seriously.)":                           280,
    "Clan War: Trailer Trashing":                             281,
    "Written by the Victor":                                  282,
    "Capture the Flags":                                      283,
    "The Chosen One":                                         284,
    "The Cold Shoulder":                                      285,
    "To Grandmother's House We Go":                           286,
    "The Great Escape":                                       287,
    "Hungry Like the Skag":                                   288,
    "Hyperion Contract #873":                                 289,
    "Medical Mystery":                                        290,
    "Medical Mystery: X-Com-municate":                        291,
    "Out of Body Experience":                                 292,
    "Hyperion Slaughter: Round 1":                            293,
    "Hyperion Slaughter: Round 2":                            294,
    "Hyperion Slaughter: Round 3":                            295,
    "Hyperion Slaughter: Round 4":                            296,
    "Hyperion Slaughter: Round 5":                            297,
    "Swallowed Whole":                                        298,
    "Too Close For Missiles":                                 299,
    "Uncle Teddy":                                            300,
    "Get to Know Jack":                                       301,
    "You Are Cordially Invited: Tea Party":                   302,
    "You Are Cordially Invited: RSVP":                        303,
    "Rock, Paper, Genocide: Corrosive Weapons!":              304,
    "Rock, Paper, Genocide: Shock Weapons!":                  305,
    "Animal Rescue: Medicine":                                306,
    "Splinter Group":                                         307,
    "Shoot This Guy in the Face":                             308,
    "Bandit Slaughter: Round 1":                              309,
    "Bandit Slaughter: Round 2":                              310,
    "Bandit Slaughter: Round 3":                              311,
    "Bandit Slaughter: Round 4":                              312,
    "Bandit Slaughter: Round 5":                              313,
    "Creature Slaughter: Round 1":                            314,
    "Creature Slaughter: Round 2":                            315,
    "Creature Slaughter: Round 3":                            316,
    "Creature Slaughter: Round 4":                            317,
    "Creature Slaughter: Round 5":                            318,
    "Monster Mash (Part 1)":                                  319,
    "Monster Mash (Part 2)":                                  320,
    "Monster Mash (Part 3)":                                  321,
    "Torture Chairs":                                         322,
    "Doctor's Orders":                                        323,
    "Rakkaholics Anonymous":                                  324,
    "Hidden Journals":                                        325,
    "Positive Self Image":                                    326,
    "Cult Following: False Idols":                            327,
    "Clan War: Reach the Dead Drop":                          328,
    "A Real Boy: Human":                                      329,
    "Demon Hunter":                                           330,
    "Rocko's Modern Strife":                                  331,
    "Animal Rescue: Food":                                    332,
    "Get Frosty":                                             333,
    "The Hunger Pangs":                                       334,
    "Special Delivery":                                       335,
    "Grandma Flexington's Story":                             336,
    "Grandma Flexington's Story: Raid Difficulty":            337,
    "The Dawn of New Pandora":                                338,
    "Winging It":                                             339,
    "Spore Chores":                                           340,
    "A Hard Place":                                           341,
    "Shooting The Moon":                                      342,
    "The Cost of Progress":                                   343,
    "Paradise Found":                                         344,
    "Claptocurrency":                                         345,
    "BFFFs":                                                  346,
    "Hypocritical Oath":                                      347,
    "Cadeuceus":                                              348,
    "My Brittle Pony":                                        349,
    "The Oddest Couple":                                      350,
    "A Most Cacophonous Lure":                                351,
    "Sirentology":                                            352,
    "Space Cowboy":                                           353,
    "The Vaughnguard":                                        354,
    "The Hunt is Vaughn":                                     355,
    "Chief Executive Overlord":                               356,
    "Echoes of the Past":                                     357,
    "A Role-Playing Game":                                    358,
    "Dwarven Allies":                                         359,
    "The Amulet":                                             360,
    "The Claptrap's Apprentice":                              361,
    "The Beard Makes The Man":                                362,
    "My Kingdom for a Wand":                                  363,
    "Critical Fail":                                          364,
    "My Dead Brother":                                        365,
    "Lost Souls":                                             366,
    "Ell in Shining Armor":                                   367,
    "Fake Geek Guy":                                          368,
    "Feed Butt Stallion":                                     369,
    "Loot Ninja":                                             370,
    "MMORPGFPS":                                              371,
    "Pet Butt Stallion":                                      372,
    "Denial, Anger, Initiative":                              373,
    "A Game of Games":                                        374,
    "Post-Crumpocalyptic":                                    375,
    "Raiders of the Last Boss":                               376,
    "Roll Insight":                                           377,
    "Tree Hugger":                                            378,
    "Winter is a Bloody Business":                            379,
    "Magic Slaughter: Round 1":                               380,
    "Magic Slaughter: Round 2":                               381,
    "Magic Slaughter: Round 3":                               382,
    "Magic Slaughter: Round 4":                               383,
    "Magic Slaughter: Round 5":                               384,
    "Magic Slaughter: Badass Round":                          385,
    "The Magic of Childhood":                                 386,
    "Find Murderlin's Temple":                                387,
    "The Sword in The Stoner":                                388,
    "The Bloody Harvest":                                     389,
    "Trick or Treat":                                         390,
    "Highway To Hell":                                        391,
    "Tier 2 Battle: Appetite for Destruction":                392,
    "Tier 3 Battle: Appetite for Destruction":                393,
    "Tier 3 Rematch: Appetite for Destruction":               394,
    "Tier 2 Battle: Bar Room Blitz":                          395,
    "Tier 3 Battle: Bar Room Blitz":                          396,
    "Battle: Bar Room Blitz":                                 397,
    "Tier 3 Rematch: Bar Room Blitz":                         398,
    "Tier 2 Battle: The Death Race":                          399,
    "Tier 3 Battle: The Death Race":                          400,
    "Battle: The Death Race":                                 401,
    "Tier 3 Rematch: The Death Race":                         402,
    "Tier 2 Battle: Twelve O' Clock High":                    403,
    "Tier 3 Battle: Twelve O' Clock High":                    404,
    "Battle: Twelve O' Clock High":                           405,
    "Tier 3 Rematch: Twelve O' Clock High":                   406,
    "Mother-Lover":                                           407,
    "Number One Fan":                                         408,
    "Commercial Appeal":                                      409,
    "My Husband the Skag":                                    410,
    "Say That To My Face":                                    411,
    "Welcome To The Jungle":                                  412,
    "Battle: Appetite for Destruction":                       413,
    "Burn, Baby, Burn":                                       414,
    "Chop Suey":                                              415,
    "A Montage":                                              416,
    "Get Your Motor Running":                                 417,
    "Eat Cookies and Crap Thunder":                           418,
    "Knockin' on Heaven's Door":                              419,
    "Breaking and Entering":                                  420,
    "Kickstart My Heart":                                     421,
    "Long Way To The Top":                                    422,
    "Gas Guzzlers":                                           423,
    "Matter Of Taste":                                        424,
    "Monster Hunter":                                         425,
    "Interview with a Vault Hunter":                          426,
    "Walking the Dog":                                        427,
    "Pete the Invincible":                                    428,
    "Totally Recall":                                         429,
    "Everybody Wants to be Wanted":                           430,
    "A History of Simulated Violence":                        431,
    "More History of Simulated Violence":                     432,
    "Dr. T and the Vault Hunters":                            433,
    "Fun, Sun, and Guns":                                     434,
    "A Match Made on Pandora":                                435,
    "Victims of Vault Hunters":                               436,
    "Learning to Love":                                       437,
    "A Warm Welcome":                                         438,
    "Message in a Bottle 2":                                  439,
    "Message in a Bottle 3":                                  440,
    "Message in a Bottle 4":                                  441,
    "Message In A Bottle 5":                                  442,
    "My Life For A Sandskiff":                                443,
    "A Study in Scarlett":                                    444,
    "Two Easy Pieces":                                        445,
    "The Hermit":                                             446,
    "Crazy About You":                                        447,
    "Whoops":                                                 448,
    "Let There Be Light":                                     449,
    "X Marks The Spot":                                       450,
    "Burying the Past":                                       451,
    "Just Desserts for Desert Deserters":                     452,
    "Treasure of the Sands":                                  453,
    "Fire Water":                                             454,
    "Freedom of Speech":                                      455,
    "I Know It When I See It":                                456,
    "Faster Than the Speed of Love":                          457,
    "Smells Like Victory":                                    458,
    "Wingman":                                                459,
    "Giving Jocko A Leg Up":                                  460,
    "Don't Copy That Floppy":                                 461,
    "Message in a Bottle 1":                                  462,
    "Hyperius the Invincible":                                463,
    "Master Gee the Invincible":                              464,
    "Ye Scurvy Dogs":                                         465,
    "Declaration Against Independents":                       466,
    "Grendel":                                                467,
    "Man's Best Friend":                                      468,
    "Catch-A-Ride, and Also Tetanus":                         469,
    "Savage Lands":                                           470,
    "Professor Nakayama, I Presume?":                         471,
    "A-Hunting We Will Go":                                   472,
    "The Fall of Nakayama":                                   473,
    "An Acquired Taste":                                      474,
    "Big Feet":                                               475,
    "Still Just a Borok in a Cage":                           476,
    "The Rakk Dahlia Murder":                                 477,
    "Egg on Your Face":                                       478,
    "Follow The Glow":                                        479,
    "Nakayama-rama":                                          480,
    "Now You See It":                                         481,
    "Ol' Pukey":                                              482,
    "Palling Around":                                         483,
    "I Like My Monsters Rare":                                484,
    "Urine, You're Out":                                      485,
    "Voracidous the Invincible":                              486,
}

loc_name_to_id = {

    # Enemies
    "Enemy WindshearWaste: Knuckle Dragger":           501,
    "Enemy SouthernShelfBay: Midgemong":               502,
    "Enemy SouthernShelf: Boom Bewm":                  503,
    "Enemy SouthernShelf: Captain Flynt":              504,
    "Enemy ThreeHornsDivide: Savage Lee":              505,
    "Enemy ThreeHornsDivide: Boll":                    506,
    "Enemy ThreeHornsValley: Doc Mercy":               507,
    "Enemy SouthpawSteam&Power: Assassin Oney":        508,
    "Enemy SouthpawSteam&Power: Assassin Wot":         509,
    "Enemy SouthpawSteam&Power: Assassin Reeth":       510,
    "Enemy SouthpawSteam&Power: Assassin Rouf":        511,
    "Enemy ThreeHornsValley: Scorch":                  512,
    "Enemy ThreeHornsValley: Incinerator Clayton":     513,
    "Enemy Dust: Gettle":                              514,
    "Enemy Dust: Mobley":                              515,
    "Enemy Dust: Black Queen":                         516,
    "Enemy ThreeHornsValley: Bad Maw":                 517,
    "Enemy BloodshotStronghold: Mad Mike":             518,
    "Enemy BloodshotRamparts: W4R-D3N":                519,
    "Enemy FrostburnCanyon: Spycho":                   520,
    "Enemy Dust: McNally":                             521,
    "Enemy Dust: Mick/Tector":                         522,
    # "Enemy Dust: Mick/Tector":                       522,
    "Enemy BloodshotStronghold: Dan":                  523,
    "Enemy BloodshotStronghold: Lee":                  524,
    "Enemy BloodshotStronghold: Mick":                 525,
    "Enemy BloodshotStronghold: Ralph":                526,
    "Enemy BloodshotStronghold: Flinter":              527,
    "Enemy TundraExpress: MadameVonBartlesby":         528,
    "Enemy EndOfTheLine: Wilhelm":                     529,
    "Enemy Fridge: LaneyWhite":                        530,
    "Enemy Fridge: Rakkman":                           531,
    "Enemy Fridge: SmashHead":                         532,
    "Enemy Fridge: Sinkhole":                          533,
    "Enemy Highlands: OldSlappy":                      534,
    "Enemy Highlands: GluttonousThresher":             535,
    "Enemy Highlands: Henry":                          536,
    "Enemy CausticCaverns: Blue":                      537,
    "Enemy CausticCaverns: BadassCreeper":             538,
    "Enemy WildlifePreserve: Tumbaa":                  539,
    "Enemy WildlifePreserve: Pimon":                   540,
    "Enemy WildlifePreserve: SonOfMothrakk":           541,
    # "Bloodwing":                                     542,
    "Enemy ThousandCuts: GOD-liath":                   543,
    "Enemy Lynchwood: DukinosMom":                     544,
    "Enemy Lynchwood: MadDog":                         545,
    "Enemy Lynchwood: SheriffNisha":                   546,
    "Enemy Lynchwood: DeputyWinger":                   547,
    "Enemy Opportunity: ForemanJasper":                548,
    "Enemy Opportunity: JackBodyDouble":               549,
    "Enemy Bunker: BNK-3R":                            550,
    "Enemy EridiumBlight: KingMong":                   551,
    "Enemy EridiumBlight: DonkeyMong":                 552,
    "Enemy SawtoothCauldron: Mortar":                  553,
    "Enemy AridNexusBoneyard: HunterHellquist":        554,
    "Enemy AridNexusBadlands: BoneHead":               555,
    "Enemy AridNexusBadlands: Saturn":                 556,
    "Enemy VaultOfTheWarrior: Warrior":                557,
    #"Enemy Hallowed Hollow: Sully the Blacksmith"     1558,
    "Enemy Hallowed Hollow: Pumpkin Kingpin":           1099,
    "Enemy Hallowed Hollow: Cryptkeeper Clark":         1100,
    "Enemy Gluttony Gulch: Chef Gouda Ramsay":          1101,
    "Enemy Gluttony Gulch: The Rat in the Hat":         1102,
    "Enemy Gluttony Gulch: Chef Brulee":                1103,
    "Enemy Gluttony Gulch: Chef Bork Bork":             1104,
    "Enemy Gluttony Gulch: Wattle Gobbler":             1105,
    "Enemy Gluttony Gulch: Glasspool, Tribute of Wurmwater":        1106,
    "Enemy Gluttony Gulch: William, Tribute of Wurmwater":          1107,
    "Enemy Gluttony Gulch: Axel, Tribute of Opportunity":           1108,
    "Enemy Gluttony Gulch: Rose, Tribute of Opportunity":           1109,
    "Enemy Gluttony Gulch: Strip, Tribute of Southern Shelf":       1110,
    "Enemy Gluttony Gulch: Flay, Tribute of Southern Shelf":        1111,
    "Enemy Gluttony Gulch: Bailly, Tribute of Sawtooth Cauldron":   1112,
    "Enemy Gluttony Gulch: Moretus, Tribute of Sawtooth Cauldron":  1113,
    "Enemy Gluttony Gulch: Cynder, Tribute of Frostburn":           1114,
    "Enemy Gluttony Gulch: Fuse, Tribute of Frostburn":             1115,
    "Enemy Gluttony Gulch: Annie, Tribute of Lunchwood":            1116,
    "Enemy Gluttony Gulch: Garret, Tribute of Lynchwood":           1117,
    "Enemy Gluttony Gulch: Fiona, Tribute of Sanctuary":            1118,
    "Enemy Gluttony Gulch: Max, Tribute of Sanctuary":              1119,
    "Enemy Marcus's Mercenary Shop: Tinder Snowflake":  1120,
    "Enemy Rotgut Distillery: Colin Zaford":            1121,
    "Enemy Rotgut Distillery: Bridget Hodunk":          1122,
    "Enemy Rotgut Distillery: BLNG Loader":             1123,
    "Enemy Rotgut Distillery: Stella":                  1124,
    "Enemy Rotgut Distillery: Ed":                      1125,
    "Enemy Rotgut Distillery: Innuendobot 5000":        1126,
    "Enemy Rotgut Distillery: Sigmand":                 1127,
    "Enemy Rotgut Distillery: Ikaroa":                  1128,
    "Enemy Rotgut Distillery: Moby":                    1129,
    #"Enemy Rotgut Distillery: Fire Crack'n":           1130,
    "Enemy Rotgut Distillery: Rue, the Love Thresher":  1131,
    "Enemy Wam Bam Island: Son of Crawmerax":           1132,
    "Enemy Wam Bam Island: Sparky Flynt":               1133,


    # Vault Symbols
    "Symbol Sanctuary: Rooftop":                             601,
    "Symbol Sanctuary: Moxxi's Corner":                      602,
    "Symbol Sanctuary: Trash Corner":                        603,
    "Symbol Sanctuary: Tire Corner":                         604,
    "Symbol Sanctuary: Parkour Door":                        605,
    "Symbol EridiumBlight: Hellsfont Crate":                 606,
    "Symbol EridiumBlight: Stairs Door":                     607,
    "Symbol EridiumBlight: Refund Building":                 608,
    "Symbol Fink's: Column":                                 609,
    "Symbol Bunker: Backside":                               610,
    "Symbol WarriorVault: Elevator Bottom":                  611,
    "Symbol SouthernShelfBay: Blackburn Cove Corner":        612,
    "Symbol SouthernShelfBay: Ice Flows Shipwreck":          613,
    "Symbol Sawtooth: Refinery Container":                   614,
    "Symbol Sawtooth: Elevator":                             615,
    "Symbol CreatureSlaughter: Crate Ceiling":               616,
    "Symbol HerosPass: Strut":                               617,
    "Symbol HerosPass: Spawn":                               618,
    "Symbol Fridge: Secret Stash":                           619,
    "Symbol Fridge: Sheetmetal Roof":                        620,
    "Symbol ThreeHornsValley: Slums Wall":                   621,
    "Symbol ThreeHornsValley: Frostsprings Wall":            622,
    "Symbol ThreeHornsValley: Frostsprings Shack":           623,
    "Symbol AridNexusBoneyard: Pipe":                        624,
    "Symbol AridNexusBoneyard: Safety":                      625,
    "Symbol WindshearWaste: Claptrap's Closet":              626,
    "Symbol ThousandCuts: Buzzard Factory":                  627,
    "Symbol ThousandCuts: No Man's Land Shack":              628,
    "Symbol Lynchwood: Gunslinger Roof":                     629,
    "Symbol Lynchwood: Main Street":                         630,
    "Symbol Highlands: Highlands Tower":                     631,
    "Symbol FriendshipGulag: Gulag Container":               632,
    "Symbol Opportunity: Construction Site":                 633,
    "Symbol Opportunity: Office Bridge":                     634,
    "Symbol ThreeHornsDivide Drydocks Corner":               635,
    "Symbol ThreeHornsDivide Billboard":                     636,
    "Symbol ThreeHornsDivide Windbreak Wall":                637,
    "Symbol Dust: Speedway Wall":                            638,
    "Symbol Dust: Buzzard Pad":                              639,
    "Symbol Dust: Moonshiner Lid":                           640,
    "Symbol CausticCaverns: Gravestone Feature":             641,
    "Symbol CausticCaverns: Bloody Ladder":                  642,
    "Symbol Bloodshot: Pizza Intercom":                      643,
    "Symbol Bloodshot: Switch Room":                         644,
    "Symbol BloodshotRamparts: Ramp":                        645,
    "Symbol Frostburn: Blisterpus Cave":                     646,
    "Symbol Frostburn: Ashmouth Pit":                        647,
    "Symbol TorgueArenaRing: Arena Wall":                    648,
    "Symbol TorgueArenaRing: Arena Ladder":                  649,
    "Symbol Beatdown: Underpass":                            650,
    "Symbol Beatdown: School Bus":                           651,
    "Symbol Forge: Smack Talker":                            652,
    "Symbol Forge: Lava":                                    653,
    "Symbol Forge: Housing":                                 654,
    "Symbol SouthernRaceway: Zer0 Poster":                   655,
    "Symbol SouthernRaceway: Maya Poster":                   656,
    "Symbol BadassCrater: Badass Highway":                   657,
    "Symbol BadassCrater: Beatdown Door":                    658,
    "Symbol BadassCrater: Billboard Lower":                  659,
    "Symbol BadassCrater: Billboard Upper":                  660,
    "Symbol HolySpirits: Bathroom":                          661,
    "Symbol HaytorsFolly: Hot Springs Crate":                662,
    "Symbol HaytorsFolly: Grendel Exit":                     663,
    "Symbol Oasis: Kronus":                                  664,
    "Symbol Oasis: Lair Exit":                               665,
    "Symbol Oasis: Lionel Docks":                            666,
    "Symbol Oasis: Coral Island":                            667,
    "Symbol WashburneRefinery: P3RV-E Lair":                 668,
    "Symbol WashburneRefinery: Forge Array":                 669,
    "Symbol Wurmwater: Rustyard Corridor":                   670,
    "Symbol Wurmwater: Scarlett's Ship":                     671,
    "Symbol Wurmwater: The Dish":                            672,
    "Symbol Rustyards: Maroonie's Clipper":                  673,
    "Symbol Rustyards: Rustyards Fence":                     674,
    "Symbol MagnysLighthouse: House":                        675,
    "Symbol MagnysLighthouse: Lighthouse":                   676,
    "Symbol LeviathansLair: Lair":                           677,
    "Symbol WildlifePreserve: Dockyard Roof":                678,
    "Symbol WildlifePreserve: Broken Boulevard":             679,
    "Symbol OreChasm: Elevator":                             680,
    "Symbol CandlerakksCragg: Elite Crossing House":         681,
    "Symbol CandlerakksCragg: Near Voracidous":              682,
    "Symbol CandlerakksCragg: Rouge's Lair":                 683,
    "Symbol Terminus: Terminus":                             684,
    "Symbol ArdortonStation: Woundspike's Lair":             685,
    "Symbol ArdortonStation: Psycho Surgery":                686,
    "Symbol ArdortonStation: Ardo Farm":                     687,
    "Symbol ArdortonStation: Dribble's Lair":                688,
    "Symbol ScyllasGrove: Low Gut Rut Wall":                 689,
    "Symbol ScyllasGrove: Urine Wall":                       690,
    "Symbol ScyllasGrove: Upper Village":                    691,
    "Symbol ScyllasGrove: Lower Village":                    692,
    "Symbol SanctuaryHole: Staircase Wall":                  693,
    "Symbol SouthernShelf: Flynt's Ship":                    694,
    "Symbol SouthernShelf: Safehouse":                       695,
    "Symbol Southpaw: Parkour":                              696,
    "Symbol Southpaw: Engine":                               697,
    "Symbol Southpaw: Ladder":                               698,
    "Symbol TerramorphousPeak: Dropdown":                    699,
    "Symbol TerramorphousPeak: Elevator":                    700,
    "Symbol EndOfTheLine: Wilhelm Wall":                     701,
    "Symbol TundraExpress: Fork Shack":                      702,
    "Symbol TundraExpress: Facility Roof":                   703,
    "Symbol Backburner: Zed's":                              704,
    "Symbol Backburner: Entrance":                           705,
    "Symbol HatredsShadow: Sir Boil":                        706,
    "Symbol HatredsShadow: Nefarious Elevator":              707,
    "Symbol HatredsShadow: Sir Mash":                        708,
    "Symbol DragonKeep: Sacrifice Staircase":                709,
    "Symbol Forest: Blood Tree Camp":                        710,
    "Symbol Forest: Glenn's Cottage":                        711,
    "Symbol ImmortalWoods: Fields of the Fallen":            712,
    "Symbol ImmortalWoods: Sacred Ruins Upper":              713,
    "Symbol ImmortalWoods: Sacred Ruins Lower":              714,
    "Symbol UnassumingDocks: Temple Shoreline":              715,
    "Symbol UnassumingDocks: Forlorn Ruins":                 716,
    "Symbol UnassumingDocks: Hamlet Building":               717,
    "Symbol WingedStorm: The Winged Storm":                  718,
    "Symbol LairOfInfiniteAgony: Platform Corridor":         719,
    "Symbol LairOfInfiniteAgony: Hall of the Dead":          720,
    "Symbol LairOfInfiniteAgony: Wailer Drop":               721,
    "Symbol HeliosFallen: Moonshot Complaint Dept":          722,
    "Symbol HeliosFallen: The Freightway":                   723,
    "Symbol HeliosFallen: Hellion Hole":                     724,
    "Symbol HeliosFallen: Munitions Loading":                725,
    "Symbol HeliosFallen: Fire Control Alpha":               726,
    "Symbol HeliosFallen: The Hold":                         727,
    "Symbol MinesOfAvarice: Ingot Processing":               728,
    "Symbol MinesOfAvarice: Cube Room":                      729,
    "Symbol MinesOfAvarice: Greedtooth's Lair":              730,
    "Symbol DahlAbandon: Simon's Perch Climb":               731,
    "Symbol DahlAbandon: Ride's End":                        732,
    "Symbol DahlAbandon: Redclaw Rise Cliff":                733,
    "Symbol DahlAbandon: The Veiny Shaft":                   734,
    "Symbol DahlAbandon: Simon's Perch Container":           735,
    "Symbol MtScarab: Test Candidate Detention":             736,
    "Symbol MtScarab: 02 Staircase":                         737,
    "Symbol MtScarab: Experimentation Room":                 738,
    "Symbol HuntersGrotto: Arizona's Lair":                  739,
    "Symbol HuntersGrotto: Grotto Lodge":                    740,
    "Symbol HuntersGrotto: Grotto Start":                    741,
    "Symbol HuntersGrotto: Dahl Door":                       742,
    "Symbol WrithingDeep: Elevator Room":                    743,
    "Symbol WrithingDeep: Southern Top":                     744,
    "Symbol WrithingDeep: Northern Top":                     745,
    "Symbol Burrows: Hyperion's Grave":                      746,
    "Symbol Burrows: Burrows Cliff":                         747,
    "Symbol MurderlinsTemple: The Nursery":                  748,
    "Symbol MurderlinsTemple: Below Murderlin":              749,
    "Symbol FlamerockRefuge: Outskirts":                     750,
    "Symbol FlamerockRefuge: Parkour":                       751,

    # Vending Machines
    "Vending Sanctuary Crimson Base: Guns":                    800,
    "Vending Sanctuary Crimson Base: Ammo Dump":               801,
    "Vending Sanctuary Zed's: Ammo Dump":                      802,
    "Vending Sanctuary Zed's: Zed's Meds 1":                   803,
    "Vending Sanctuary Zed's: Zed's Meds 2":                   804,
    "Vending Sanctuary Marcus's: Zed's Meds":                  805,
    "Vending Sanctuary Marcus's: Ammo Dump":                   806,
    "Vending Sanctuary Marcus's: Marcus":                      807,
    "Vending FriendshipGulag: Zed's Meds":                     808,
    "Vending FriendshipGulag: Ammo Dump":                      809,
    "Vending Dust Ellie's: Zed's Meds":                        810,
    "Vending Dust Ellie's: Ammo Dump":                         811,
    "Vending SouthernShelf Hammerlock's: Guns":                812,
    "Vending SouthernShelf Liar's: Ammo Dump":                 813,
    "Vending SouthernShelf Liar's: Zed's Meds":                814,
    "Vending SouthernShelf Safehouse: Zed's Meds":             815,
    "Vending SouthernShelf Dragon: Zed's Meds":                816,
    "Vending SouthernShelf Dragon: Ammo Dump":                 817,
    "Vending SouthernShelfBay Spawn: Ammo Dump":               818,
    "Vending SouthernShelfBay Spawn: Zed's Meds":              819,
    "Vending SouthernShelfBay Cove: Guns":                     820,
    "Vending SouthernShelfBay Cove: Ammo Dump":                821,
    "Vending SouthernShelfBay Cove: Zed's Meds":               822,
    "Vending ThreeHornsDivide Jump: Ammo Dump":                823,
    "Vending ThreeHornsDivide Jump: Zed's Meds":               824,
    "Vending ThreeHornsDivide Crossroads: Guns":               825,
    "Vending ThreeHornsDivide Crossroads: Ammo Dump":          826,
    "Vending ThreeHornsDivide Crossroads: Zed's Meds":         827,
    "Vending ThreeHornsValley Motel: Guns":                    828,
    "Vending ThreeHornsValley Motel: Ammo Dump":               829,
    "Vending ThreeHornsValley Motel: Zed's Meds":              830,
    "Vending Southpaw: Ammo Dump":                             831,
    "Vending Southpaw: Zed's Meds":                            832,
    "Vending Frostburn Spawn: Ammo Dump":                      833,
    "Vending Frostburn Spawn: Zed's Meds":                     834,
    "Vending Frostburn Firehawk: Ammo Dump":                   835,
    "Vending Frostburn Firehawk: Zed's Meds":                  836,
    "Vending Stronghold: Ammo Dump":                           837,
    "Vending Stronghold: Zed's Meds":                          838,
    "Vending Ramparts: Ammo Dump":                             839,
    "Vending Ramparts: Zed's Meds":                            840,
    "Vending Tundra Spawn: Ammo Dump":                         841,
    "Vending Tundra Spawn: Zed's Meds":                        842,
    "Vending Tundra Farm: Guns":                               843,
    "Vending Tundra Tina: Ammo Dump":                          844,
    "Vending EndOfTheLine: Ammo Dump":                         845,
    "Vending EndOfTheLine: Zed's Meds":                        846,
    "Vending Fridge Spawn: Ammo Dump":                         847,
    "Vending Fridge Spawn: Zed's Meds":                        848,
    "Vending Fridge Elevator: Ammo Dump":                      849,
    "Vending Fridge Elevator: Zed's Meds":                     850,
    "Vending Fink's: Guns":                                    851,
    "Vending Fink's: Ammo Dump":                               852,
    "Vending Fink's: Zed's Meds":                              853,
    "Vending Outwash: Ammo Dump":                              854,
    "Vending Outwash: Zed's Meds":                             855,
    "Vending Highlands Bridge: Ammo Dump":                     856,
    "Vending Highlands Bridge: Zed's Meds":                    857,
    "Vending Highlands Overlook: Guns":                        858,
    "Vending Highlands Overlook: Ammo Dump":                   859,
    # "Vending Highlands Overlook: Zed's Meds":                860,
    # "Vending Extraction Plant: Zed's Meds":                  861,
    # "Vending Hyperion Bridge: Zed's Meds":                   862,
    "Vending HolySpirits: Guns":                               863,
    "Vending HolySpirits: Ammo Dump":                          864,
    "Vending HolySpirits: Zed's Meds":                         865,
    "Vending Dust Speedway: Ammo Dump":                        866,
    "Vending Dust Speedway: Zed's Meds":                       867,
    "Vending Dust Steve: Ammo Dump":                           868,
    "Vending Dust Steve: Zed's Meds":                          869,
    "Vending SanctuaryHole: Ammo Dump":                        870,
    "Vending SanctuaryHole: Zed's Meds":                       871,
    "Vending Caverns Spawn: Ammo Dump":                        872,
    "Vending Caverns Spawn: Zed's Meds":                       873,
    "Vending Caverns Shortcut: Guns":                          874,
    "Vending Preserve Spawn: Ammo Dump":                       875,
    "Vending Preserve Spawn: Zed's Meds":                      876,
    "Vending Preserve Halfway: Ammo Dump":                     877,
    "Vending Preserve Halfway: Zed's Meds":                    878,
    "Vending Creature: Ammo Dump":                             879,
    "Vending Creature: Zed's Meds":                            880,
    "Vending Thousand: Ammo Dump":                             881,
    "Vending Thousand: Zed's Meds":                            882,
    "Vending Lynchwood Spawn: Ammo Dump":                      883,
    "Vending Lynchwood Spawn: Zed's Meds":                     884,
    "Vending Lynchwood Gunslinger: Guns":                      885,
    "Vending Opportunity Spawn: Guns":                         886,
    "Vending Opportunity Spawn: Ammo Dump":                    887,
    "Vending Opportunity Spawn: Zed's Meds":                   888,
    "Vending Opportunity Office: Ammo Dump":                   889,
    "Vending Opportunity Office: Zed's Meds":                  890,
    "Vending Opportunity Square: Ammo Dump":                   891,
    "Vending Opportunity Square: Zed's Meds":                  892,
    "Vending Opportunity Residential: Guns":                   893,
    "Vending Opportunity Residential: Ammo Dump":              894,
    "Vending Bunker: Ammo Dump":                               895,
    "Vending Bunker: Zed's Meds":                              896,
    "Vending Blight Spawn: Ammo Dump":                         897,
    "Vending Blight Spawn: Zed's Meds":                        898,
    "Vending Blight Extraction: Ammo Dump":                    899,
    "Vending Blight Extraction: Zed's Meds":                   900,
    "Vending Blight Refinery: Guns":                           901,
    "Vending Blight Refinery: Ammo Dump":                      902,
    "Vending Blight Refinery: Zed's Meds":                     903,
    "Vending OreChasm: Guns":                                  904,
    "Vending OreChasm: Ammo Dump":                             905,
    "Vending OreChasm: Zed's Meds":                            906,
    "Vending Sawtooth Spawn: Ammo Dump":                       907,
    "Vending Sawtooth Spawn: Zed's Meds":                      908,
    "Vending Sawtooth Elevator: Ammo Dump":                    909,
    "Vending Boneyard Spawn: Ammo Dump":                       910,
    "Vending Boneyard Spawn: Zed's Meds":                      911,
    "Vending Badlands Fyrestone: Ammo Dump":                   912,
    "Vending Badlands Fyrestone: Zed's Meds":                  913,
    "Vending Badlands Baha: Guns":                             914,
    "Vending HerosPass Spawn: Ammo Dump":                      915,
    "Vending HerosPass Spawn: Zed's Meds":                     916,
    "Vending Warrior: Ammo Dump":                              917,
    "Vending Warrior: Zed's Meds":                             918,
    "Vending Terramorphous: Guns":                             919,
    "Vending Terramorphous: Ammo Dump":                        920,
    "Vending Terramorphous: Zed's Meds":                       921,
    # "Vending Oasis Town: Seraph Vendor":                     922,
    "Vending Oasis Town: Guns":                                923,
    "Vending Oasis Town: Ammo Dump":                           924,
    "Vending Oasis Town: Zed's Meds":                          925,
    "Vending Wurmwater Oasis Door: Ammo Dump":                 926,
    "Vending Wurmwater Oasis Door: Zed's Meds":                927,
    "Vending Wurmwater Canyon: Guns":                          928,
    "Vending Wurmwater Canyon: Ammo Dump":                     929,
    "Vending Wurmwater Fen: Ammo Dump":                        930,
    "Vending Wurmwater Ship: Guns":                            931,
    "Vending Wurmwater Ship: Ammo Dump":                       932,
    "Vending Wurmwater Ship: Zed's Meds":                      933,
    "Vending Wurmwater Rustyard: Guns":                        934,
    "Vending Hayters Spawn: Guns":                             935,
    "Vending Hayters Spawn: Ammo Dump":                        936,
    "Vending Hayters Spawn: Zed's Meds":                       937,
    "Vending Hayters Gee: Ammo Dump":                          938,
    "Vending Hayters Gee: Zed's Meds":                         939,
    "Vending Rustyards Spawn: Ammo Dump":                      940,
    "Vending Rustyards Spawn: Zed's Meds":                     941,
    "Vending Washburne Spawn: Ammo Dump":                      942,
    "Vending Washburne Spawn: Zed's Meds":                     943,
    "Vending Washburne Hyperius: Ammo Dump":                   944,
    "Vending Washburne Hyperius: Zed's Meds":                  945,
    "Vending Magnys Spawn: Ammo Dump":                         946,
    "Vending Magnys Spawn: Zed's Meds":                        947,
    "Vending Leviathan Body: Ammo Dump":                       948,
    "Vending Leviathan Body: Zed's Meds":                      949,
    "Vending Leviathan Lair: Ammo Dump":                       950,
    "Vending Leviathan Lair: Zed's Meds":                      951,
    "Vending Crater Spawn: Ammo Dump":                         952,
    "Vending Crater Spawn: Zed's Meds":                        953,
    # "Vending Crater Town: Seraph Vendor":                    954,
    "Vending Crater Town: Ammo Dump":                          955,
    "Vending Crater Town: Zed's Meds":                         956,
    "Vending Crater Forge: Torgue Vendor":                     957,
    "Vending Crater Forge: Ammo Dump":                         958,
    "Vending Crater Forge: Zed's Meds":                        959,
    "Vending Arena Inner: Torgue Vendor":                      960,
    "Vending Arena Inner: Ammo Dump":                          961,
    "Vending Arena Inner: Zed's Meds":                         962,
    "Vending Beatdown Spawn: Torgue Vendor":                   963,
    "Vending Beatdown Spawn: Ammo Dump":                       964,
    "Vending Beatdown Spawn: Zed's Meds":                      965,
    "Vending Beatdown Underpass: Torgue Vendor":               966,
    "Vending Beatdown Underpass: Ammo Dump":                   967,
    "Vending Beatdown Underpass: Zed's Meds":                  968,
    "Vending Pete's: Torgue Vendor":                           969,
    "Vending Pete's: Ammo Dump":                               970,
    "Vending Pete's: Zed's Meds":                              971,
    "Vending BadassBar: Torgue Vendor":                        972,
    "Vending BadassBar: Ammo Dump":                            973,
    "Vending BadassBar: Zed's Meds":                           974,
    "Vending Raceway: Torgue Vendor":                          975,
    "Vending Raceway: Ammo Dump":                              976,
    "Vending Raceway: Zed's Meds":                             977,
    "Vending Forge Spawn: Torgue Vendor":                      978,
    "Vending Forge Spawn: Ammo Dump":                          979,
    "Vending Forge Spawn: Zed's Meds":                         980,
    "Vending Forge Flyboy: Ammo Dump":                         981,
    "Vending Forge Flyboy: Zed's Meds":                        982,
    # "Vending Grotto Lodge: Seraph Vendor":                   983,
    "Vending Grotto Lodge: Guns":                              984,
    "Vending Grotto Lodge: Ammo Dump":                         985,
    "Vending Grotto Lodge: Zed's Meds":                        986,
    "Vending Scylla's Entrance: Guns":                         987,
    "Vending Scylla's Entrance: Ammo Dump":                    988,
    "Vending Scylla's Entrance: Zed's Meds":                   989,
    "Vending Scylla's Pukey: Zed's Meds":                      990,
    "Vending Ardorton Entrance: Ammo Dump":                    991,
    "Vending Ardorton Entrance: Zed's Meds":                   992,
    "Vending Ardorton Exit: Ammo Dump":                        993,
    "Vending Ardorton Exit: Zed's Meds":                       994,
    "Vending Crag Spawn: Ammo Dump":                           995,
    "Vending Crag Spawn: Zed's Meds":                          996,
    "Vending Crag Voracidous: Ammo Dump":                      997,
    "Vending Crag Voracidous: Zed's Meds":                     998,
    "Vending Terminus Entrance: Ammo Dump":                    999,
    "Vending Terminus Entrance: Zed's Meds":                  1000,
    # "Vending Flamerock Refuge: Seraph Vendor":              1001,
    "Vending Flamerock Refuge: Guns/Cannons":                 1002,
    "Vending Flamerock Refuge: Ammo Dump/Missiles":           1003,
    "Vending Flamerock Refuge: Zed's Apothecary":             1004,
    "Vending Forest Spawn: Ammo Dump/Missiles":               1005,
    "Vending Forest Spawn: Zed's Apothecary":                 1006,
    "Vending Immortal Spawn: Ammo Dump/Missiles":             1007,
    "Vending Immortal Spawn: Zed's Apothecary":               1008,
    "Vending Immortal Vitality Grove: Ammo Dump/Missiles":    1009,
    "Vending Immortal Vitality Grove: Zed's Apothecary":      1010,
    "Vending Avarice Spawn: Ammo Dump/Missiles":              1011,
    "Vending Avarice Spawn: Zed's Apothecary":                1012,
    "Vending Avarice Greedtooth: Ammo Dump/Missiles":         1013,
    "Vending Avarice Greedtooth: Zed's Apothecary":           1014,
    "Vending Shadow Spawn: Ammo Dump/Missiles":               1015,
    "Vending Shadow Spawn: Zed's Apothecary":                 1016,
    "Vending Handsome Bridge: Guns/Cannons":                  1017,
    "Vending Handsome Bridge: Ammo Dump/Missiles":            1018,
    "Vending Handsome Bridge: Zed's Apothecary":              1019,
    "Vending Agony Spawn: Ammo Dump/Missiles":                1020,
    "Vending Agony Spawn: Zed's Apothecary":                  1021,
    "Vending Agony Daughter: Ammo Dump/Missiles":             1022,
    "Vending Agony Daughter: Zed's Apothecary":               1023,
    # "Vending Agony Hall of the Dead: Mr. Miz":              1024,
    "Vending DragonKeep: Ammo Dump/Missiles":                 1025,
    "Vending DragonKeep: Zed's Apothecary":                   1026,
    "Vending WingedStorm: Guns/Cannons":                      1027,
    "Vending WingedStorm: Ammo Dump/Missiles":                1028,
    "Vending WingedStorm: Zed's Apothecary":                  1029,
    "Vending Murderlin's Temple: Guns/Cannons":               1030,
    "Vending Murderlin's Temple: Ammo Dump/Missiles":         1031,
    "Vending Murderlin's Temple: Zed's Apothecary":           1032,
    "Vending HallowedHollow Entrance: Ammo Dump":             1033,
    "Vending HallowedHollow Entrance: Zed's Meds":            1034,
    "Vending HallowedHollow Kingpin Approach: Zed's Meds":    1035,
    "Vending HallowedHollow Kingpin Approach: Ammo Dump":     1036,
    "Vending GlutGulch Entrance: Guns":                       1037,
    "Vending GlutGulch Entrance: Ammo Dump":                  1038,
    "Vending GlutGulch Entrance: Zed's Meds":                 1039,
    "Vending GlutGulch Kitchen: Ammo Dump":                   1040,
    "Vending GlutGulch Stabber Jabber: Guns":                 1041,
    "Vending GlutGulch Tribute Station: Guns":                1042,
    "Vending GlutGulch Tribute Station: Zed's Meds":          1043,
    "Vending GlutGulch Tribute Station: Ammo Dump":           1044,
    "Vending MercenaryDay Entrance: Guns":                    1045,
    "Vending MercenaryDay Entrance: Ammo Dump":               1046,
    "Vending MercenaryDay Entrance: Zed's Meds":              1047,
    "Vending MercenaryDay Tinder Arena: Zed's Meds":          1048,
    "Vending MercenaryDay Tinder Arena: Ammo Dump":           1049,
    "Vending Distillery Entrance: Zed's Meds":                1050,
    "Vending Distillery Entrance: Ammo Dump":                 1051,
    "Vending Distillery Pot of Gold: Ammo Dump":              1052,
    "Vending Distillery Wedding Venue: Zed's Meds":           1053,
    "Vending Distillery Wedding Venue: Ammo Dump":            1054,
    "Vending WamBam Entrance: Ammo Dump":                     1055,
    "Vending WamBam Entrance: Zed's Meds":                    1056,
    "Vending WamBam Water Wheel: Zed's Meds":                 1057,
    "Vending WamBam Water Wheel: Ammo Dump":                  1058,
    "Vending WamBam Son's Arena: Ammo Dump":                  1059,
    "Vending WamBam Son's Arena: Zed's Meds":                 1060,
    "Vending Backburner Entrance: Ammo Dump":                 1061,
    "Vending Backburner Entrance: Zed's Meds":                1062,
    "Vending Backburner Vaughn's HQ: Guns":                   1063,
    "Vending Backburner Vaughn's HQ: Ammo Dump":              1064,
    "Vending Backburner Vaughn's HQ: Zed's Meds":             1065,
    "Vending Backburner Marcus: Guns":                        1066,
    "Vending Backburner Marcus: Ammo Dump":                   1067,
    "Vending DahlAbandon Entrance: Ammo dump":                1068,
    "Vending DahlAbandon Entrance: Zed's Meds":               1069,
    "Vending DahlAbandon Mine Door: Ammo Dump":               1070,
    "Vending DahlAbandon Mine Door: Zed's Meds":              1071,
    "Vending Burrows Entrance: Ammo Dump":                    1072,
    "Vending Burrows Entrance: Zed's Meds":                   1073,
    "Vending HeliosFallen Entrance: Ammo Dump":               1074,
    "Vending HeliosFallen Entrance: Zed's Meds":              1075,
    "Vending HeliosFallen Munitions Loading: Ammo Dump":      1076,
    "Vending HeliosFallen Munitions Loading: Zed's Meds":     1077,
    "Vending HeliosFallen The Arsenal: Ammo Dump":            1078,
    "Vending HeliosFallen The Arsenal: Zed's Meds":           1079,
    "Vending Mt.Scarab Entrance: Ammo Dump":                  1080,
    "Vending Mt.Scarab Entrance: Zed's Meds":                 1081,
    "Vending Mt.Scarab Observation Deck: Ammo Dump":          1082,
    "Vending Mt.Scarab Observation Deck: Zed's Meds":         1083,
    # "Vending Paradise Sanctum Entrance: Ammo Dump":         1084,
    # "Vending Paradise Sanctum Entrance: Zed's Meds":        1085,
    # "Vending Paradise Sanctum Marcus Munitions: Guns":      1086,
    # "Vending Paradise Sanctum Marcus Munitions: Zed's Meds":  1087,
    # "Vending Paradise Sanctum Hector: Ammo Dump":           1088,
    # "Vending Paradise Sanctum Hector: Zed's Meds":          1089,
    "Vending WrithingDeep: Ammo Dump":                        1090,
    "Vending WrithingDeep: Zed's Meds":                       1091,
    "Vending Digistruct Spawn: Guns":                         1092,
    "Vending Digistruct Spawn: Ammo Dump":                    1093,
    "Vending Digistruct Spawn: Zed's Meds":                   1094,
    "Vending DigistructInner Butcher Base: Ammo Dump":        1095,
    # "Vending DigistructInner Area of Anguish: Ammo Dump":   1096,
    # "Vending DigistructInner Area of Anguish: Zed's Meds":  1097,
    # "Vending DigistructInner Tower of Torment: Ammo Dump":  1098,
}


item_name_to_id = {
    "3 Skill Points":                     1,
    "Progressive Money Cap":              2,
    "Weapon Slot":                        3,
    "$100":                               4,
    "10 Eridium":                         5,

    "Progressive Jump":                   6,
    "Melee":                              7,
    "Crouch":                             8,
    "Sprint":                             9,
    "Gear Leveler":                      10,
    "Vehicle Fire":                      11,

    # Map Areas
    # "Travel: Windshear Waste":                   501,
    "Travel: Arid Nexus Boneyard":                 502,
    "Travel: The Holy Spirits":                    503,
    "Travel: Southpaw Steam & Power":              504,
    "Travel: Sanctuary Hole":                      505,
    "Travel: Hero's Pass":                         506,
    "Travel: Bloodshot Stronghold":                507,
    "Travel: Three Horns Valley":                  508,
    "Travel: Sanctuary":                           509,
    "Travel: Thousand Cuts":                       510,
    "Travel: End of the Line":                     511,
    "Travel: Wildlife Exploitation Preserve":      512,
    "Travel: Terramorphous Peak":                  513,
    "Travel: Tundra Express":                      514,
    "Travel: The Fridge":                          515,
    "Travel: Fink's Slaughterhouse":               516,
    "Travel: Southern Shelf Bay":                  517,
    "Travel: Frostburn Canyon":                    518,
    "Travel: Three Horns Divide":                  519,
    "Travel: Highlands":                           520,
    "Travel: Natural Selection Annex":             521,
    "Travel: The Dust":                            522,
    "Travel: Friendship Gulag":                    523,
    "Travel: Opportunity":                         524,
    "Travel: Bloodshot Ramparts":                  525,
    "Travel: Arid Nexus Badlands":                 526,
    "Travel: Southern Shelf":                      527,
    "Travel: Highlands Outwash":                   528,
    "Travel: Caustic Caverns":                     529,
    "Travel: Lynchwood":                           530,
    "Travel: Sawtooth Cauldron":                   531,
    "Travel: Ore Chasm":                           532,
    "Travel: The Bunker":                          533,
    "Travel: Control Core Angel":                  534,
    "Travel: Vault of the Warrior":                535,
    "Travel: Eridium Blight":                      536,
    "Travel: Gluttony Gulch":                      537,
    "Travel: Marcus's Mercenary Shop":             538,
    "Travel: Helios Fallen":                       539,
    "Travel: FFS Boss Fight":                      540,
    "Travel: The Backburner":                      541,
    "Travel: FFS Intro Sanctuary":                 542,
    "Travel: Dahl Abandon":                        543,
    "Travel: Mt. Scarab Research Center":          544,
    "Travel: The Burrows":                         545,
    "Travel: Writhing Deep":                       546,
    "Travel: The Forest":                          547,
    "Travel: Immortal Woods":                      548,
    "Travel: Dragon Keep":                         549,
    "Travel: Unassuming Docks":                    550,
    "Travel: Flamerock Refuge":                    551,
    "Travel: Hatred's Shadow":                     552,
    "Travel: Lair of Infinite Agony":              553,
    "Travel: Murderlin's Temple":                  554,
    "Travel: Mines of Avarice":                    555,
    "Travel: The Winged Storm":                    556,
    "Travel: Hallowed Hollow":                     557,
    "Travel: Torgue Arena Ring":                   558,
    "Travel: Torgue Arena":                        559,
    "Travel: The Beatdown":                        560,
    "Travel: The Forge":                           561,
    "Travel: Badass Crater":                       562,
    "Travel: Southern Raceway":                    563,
    "Travel: Pyro Pete's Bar":                     564,
    "Travel: Baddass Crater Bar":                  565,
    "Travel: Digistruct Peak":                     566,
    "Travel: Wam Bam Island":                      567,
    "Travel: Rotgut Distillery":                   568,
    "Travel: The Leviathan's Lair":                569,
    "Travel: Washburne Refinery":                  570,
    "Travel: Wurmwater":                           571,
    "Travel: Magnys Lighthouse":                   572,
    "Travel: The Rustyards":                       573,
    "Travel: Haytor's Folly":                      574,
    "Travel: Oasis":                               575,
    "Travel: Ardorton Station":                    576,
    "Travel: Hunter's Grotto":                     577,
    "Travel: Candlerakk's Cragg":                  578,
    "Travel: Terminus":                            579,
    "Travel: Scylla's Grove":                      580,

    # Traps
    "Trap Spawn: Saturn":                     600,
    "Trap Spawn: Black Queen":                601,
    "Trap Spawn: Assassins":                  602,
    "Trap Spawn: Dukino's Mom":               603,
    "Trap Spawn: Doc Mercy":                  604,
    "Trap Spawn: Creeper":                    605,
}

# stitch dictionaries together

loc_name_to_id.update(gear_kind_to_id)
loc_name_to_id.update(level_name_to_id)
loc_name_to_id.update({"Quest: " + k : v for k, v in quest_name_to_id.items()})

item_name_to_id.update(gear_kind_to_id)
item_name_to_id.update({"Quest Reward: " + k : v for k, v in quest_name_to_id.items()})

loc_id_to_name = {id: name for name, id in loc_name_to_id.items()}
item_id_to_name = {id: name for name, id in item_name_to_id.items()}
