import unrealsdk
from mods_base import get_pc

challenge_dict = {
    'GD_Anemone_Challenges.Challenges.Challenge_Kill_DoItForTheVine':                      "Challenge LilithDLC: Do It For The Vine",
    'GD_Anemone_Challenges.Challenges.Challenge_Kill_EveryCorner':                         "Challenge LilithDLC: Fertile Ground",
    'GD_Anemone_Challenges.Challenges.Challenge_Kill_FlowerPower':                         "Challenge LilithDLC: Flower Power",
    'GD_Anemone_Challenges.Challenges.Challenge_Kill_HaderaxTheInvincible':                "Challenge LilithDLC: Haderax The Invincible",
    'GD_Anemone_Challenges.Challenges.Challenge_Kill_LetItGo':                             "Challenge LilithDLC: Let It Grow",
    'GD_Anemone_Challenges.Challenges.Challenge_Kill_Tanksbutnotanks':                     "Challenge LilithDLC: Tanks But No Tanks",
    'GD_Anemone_Challenges.Challenges.Challenge_Kill_YouStartedIt':                        "Challenge LilithDLC: You Started It",
    'GD_Anemone_Challenges.LevelChallenges.Backburner_Echos':                              "Challenge Backburner: Make Yourself At Home",
    'GD_Anemone_Challenges.LevelChallenges.Backburner_FandirFiction':                      "Challenge Backburner: Fandir Fiction",
    'GD_Anemone_Challenges.LevelChallenges.Backburner_Harmville':                          "Challenge Backburner: Harmville",
    'GD_Anemone_Challenges.LevelChallenges.Backburner_Slagenstein':                        "Challenge Backburner: The Burdens of Creation",
    'GD_Anemone_Challenges.LevelChallenges.DahlAbandons_Echos':                            "Challenge DahlAbandon: Abandoned Records",
    'GD_Anemone_Challenges.LevelChallenges.DahlMine_Echos':                                "Challenge DahlAbandon: The Path to Paradise",
    'GD_Anemone_Challenges.LevelChallenges.Helios_ButtStomped':                            "Challenge HeliosFallen: Butt Stomped",
    'GD_Anemone_Challenges.LevelChallenges.Helios_Echos':                                  "Challenge HeliosFallen: Corporate Droning",
    'GD_Anemone_Challenges.LevelChallenges.Helios_Vaugnsport':                             "Challenge HeliosFallen: Serve, Spike, Slaughter",
    'GD_Anemone_Challenges.LevelChallenges.Helios_VaultRoy':                               "Challenge HeliosFallen: Cult of the Vault",
    'GD_Anemone_Challenges.LevelChallenges.MT_Scarab_Echos':                               "Challenge MtScarab: Soliloquy Scientific",
    'GD_Anemone_Challenges.LevelChallenges.OldDust_DahlMine':                              "Challenge DahlAbandon: Mine, Dahl Mine!",
    'GD_Anemone_Challenges.LevelChallenges.OldDust_HoldTheDoor':                           "Challenge DahlAbandon: Hold The Door!",
    'GD_Anemone_Challenges.LevelChallenges.OldDust_PayForHint':                            "Challenge DahlAbandon: Out of Scope",
    'GD_Anemone_Challenges.LevelChallenges.OldDust_VaultRoy':                              "Challenge DahlAbandon: Cult of the Vault",
    'GD_Anemone_Challenges.LevelChallenges.ResearchCenter_ForScience':                     "Challenge MtScarab: For Science!",
    'GD_Anemone_Challenges.LevelChallenges.ResearchCenter_GaseousCassius':                 "Challenge MtScarab: Gaseous Cassius",
    'GD_Anemone_Challenges.LevelChallenges.ResearchCenter_NoPeeking':                      "Challenge MtScarab: No Peeking",
    'GD_Anemone_Challenges.LevelChallenges.ResearchCenter_VaultRoy':                       "Challenge MtScarab: Cult of the Vault",
    'GD_Anemone_Challenges.LevelChallenges.SandwormCavern_Echos':                          "Challenge Burrows: Dangers Deified",
    'GD_Anemone_Challenges.LevelChallenges.SandwormCavern_Grranglaargll':                  "Challenge Burrows: Grrang'laarg'll (Queen's Treasure)",
    'GD_Anemone_Challenges.LevelChallenges.SandwormCavern_NeverEnoughTools':               "Challenge Burrows: Never Enough Tools",
    'GD_Anemone_Challenges.LevelChallenges.SandwormCavern_Timber':                         "Challenge Burrows: Timber!",
    'GD_Anemone_Challenges.LevelChallenges.SandwormCavern_VaultRoy':                       "Challenge Burrows: Cult of the Vault",
    'GD_Anemone_Challenges.LevelChallenges.SandwormLair_DuneRaider':                       "Challenge WrithingDeep: Dune Raider",
    'GD_Anemone_Challenges.LevelChallenges.SandwormLair_VaultRoy':                         "Challenge WrithingDeep: Cult of the Vault",
    'GD_Anemone_Challenges.LevelChallenges.TheBackburner_VaultRoy':                        "Challenge Backburner: Cult of the Vault",
    'GD_Aster_Challenges.Challenges.Challenge_Aster_KillDragons':                          "Challenge TinaDLC: Fus Roh Die",
    'GD_Aster_Challenges.Challenges.Challenge_Aster_KillDwarves':                          "Challenge TinaDLC: Scot-Free",
    'GD_Aster_Challenges.Challenges.Challenge_Aster_KillGolems':                           "Challenge TinaDLC: Rock Out With Your Rock Out",
    'GD_Aster_Challenges.Challenges.Challenge_Aster_KillKnights':                          "Challenge TinaDLC: Knighty Knight",
    'GD_Aster_Challenges.Challenges.Challenge_Aster_KillMimics':                           "Challenge TinaDLC: Can't Fool Me",
    'GD_Aster_Challenges.Challenges.Challenge_Aster_KillOrcs':                             "Challenge TinaDLC: Orcs Should Perish",
    'GD_Aster_Challenges.Challenges.Challenge_Aster_KillSkeletons':                        "Challenge TinaDLC: Bone Breaker",
    'GD_Aster_Challenges.Challenges.Challenge_Aster_KillSpiders':                          "Challenge TinaDLC: Ew Ew Ew Ew",
    'GD_Aster_Challenges.Challenges.Challenge_Aster_KillTreants':                          "Challenge TinaDLC: Cheerful Green Giants",
    'GD_Aster_Challenges.Challenges.Challenge_Aster_KillWizards':                          "Challenge TinaDLC: Magical Massacre",
    'GD_Aster_Challenges.LevelChallenges.CastleExterior_VaultRoy':                         "Challenge HatredsShadow: Cult of the Vault",
    'GD_Aster_Challenges.LevelChallenges.CastleKeep_SacrificialAltar':                     "Challenge DragonKeep: Blood for Blood",
    'GD_Aster_Challenges.LevelChallenges.CastleKeep_VaultRoy':                             "Challenge DragonKeep: Cult of the Vault",
    'GD_Aster_Challenges.LevelChallenges.DarkForest_Fluffybutt':                           "Challenge Forest: SO. CUTE.",
    'GD_Aster_Challenges.LevelChallenges.DarkForest_OrcDecorations':                       "Challenge Forest: Extreme Orc Makeover",
    'GD_Aster_Challenges.LevelChallenges.DarkForest_VaultRoy':                             "Challenge Forest: Cult of the Vault",
    'GD_Aster_Challenges.LevelChallenges.DeadForest_VaultRoy':                             "Challenge ImmortalWoods: Cult of the Vault",
    'GD_Aster_Challenges.LevelChallenges.Docks_SpatulaKhan':                               "Challenge UnassumingDocks: The Taste of War",
    'GD_Aster_Challenges.LevelChallenges.Docks_VaultRoy':                                  "Challenge UnassumingDocks: Cult of the Vault",
    'GD_Aster_Challenges.LevelChallenges.DungeonRaid_VaultRoy':                            "Challenge WingedStorm: Cult of the Vault",
    'GD_Aster_Challenges.LevelChallenges.Dungeon_SpiderQueen':                             "Challenge LairOfInfiniteAgony: A Single Deadly Bite",
    'GD_Aster_Challenges.LevelChallenges.Dungeon_VaultRoy':                                "Challenge LairOfInfiniteAgony: Cult of the Vault",
    'GD_Aster_Challenges.LevelChallenges.Mines_FloatingRock':                              "Challenge MinesOfAvarice: The Floor is Lava",
    'GD_Aster_Challenges.LevelChallenges.Mines_VaultRoy':                                  "Challenge MinesOfAvarice: Cult of the Vault",
    'GD_Aster_Challenges.LevelChallenges.TempleSlaughter_Orc':                             "Challenge Murderlin's: Work! Work! Work!",
    'GD_Aster_Challenges.LevelChallenges.TempleSlaughter_VaultRoy':                        "Challenge Murderlin's: Cult of the Vault",
    'GD_Aster_Challenges.LevelChallenges.Village_SmashingPumpkins':                        "Challenge Flamerock: Smashin' Pumpkins",
    'GD_Aster_Challenges.LevelChallenges.Village_VaultRoy':                                "Challenge Flamerock: Cult of the Vault",
    'GD_Challenges.Dueling.DuelsWon_HatersGonnaHate':                                      "Challenge Misc: Haters Gonna Hate",
    'GD_Challenges.Economy.Economy_BuyItemsWithEridium':                                   "Challenge Money: Whaddaya Buyin'?",
    'GD_Challenges.Economy.Economy_MoneySaved':                                            "Challenge Money: For the Hoard!",
    'GD_Challenges.Economy.Economy_PurchaseItemsOfTheDay':                                 "Challenge Money: Limited-Time Offer",
    'GD_Challenges.Economy.Economy_SellItems':                                             "Challenge Money: Wholesale",
    'GD_Challenges.Economy.General_MoneyFromCashDrops':                                    "Challenge Money: Dolla Dolla Bills, Y'all",
    'GD_Challenges.Economy.Trade_ItemsWithPlayers':                                        "Challenge Money: Psst, Hey Buddy...",
    'GD_Challenges.GeneralCombat.Barrels_KillEnemies':                                     "Challenge Combat: Not Full of Monkeys",
    'GD_Challenges.GeneralCombat.General_RoundsFired':                                     "Challenge Combat: Knee-Deep in Brass",
    'GD_Challenges.GeneralCombat.Kills_AtDay':                                             "Challenge Combat: Afternoon Delight",
    'GD_Challenges.GeneralCombat.Kills_AtNight':                                           "Challenge Combat: ...I Got to Boogie",
    'GD_Challenges.GeneralCombat.Kills_FromCrits':                                         "Challenge Combat: Critical Acclaim",
    'GD_Challenges.GeneralCombat.Player_KillsWithActionSkill':                             "Challenge Combat: ...To Pay the Bills",
    'GD_Challenges.GeneralCombat.Tediore_DamageFromReloads':                               "Challenge Combat: Gun Slinger",
    'GD_Challenges.GeneralCombat.Tediore_KillWithReload':                                  "Challenge Combat: Boomerbang",
    'GD_Challenges.Grenades.Grenade_Kills':                                                "Challenge Grenade: Pull the Pin",
    'GD_Challenges.Grenades.Grenade_KillsAoEoTType':                                       "Challenge Grenade: Chemical Sprayer",
    'GD_Challenges.Grenades.Grenade_KillsBouncing':                                        "Challenge Grenade: Woah, Black Betty",
    'GD_Challenges.Grenades.Grenade_KillsMirvType':                                        "Challenge Grenade: EXPLOOOOOSIONS!",
    'GD_Challenges.Grenades.Grenade_KillsSingularityType':                                 "Challenge Grenade: Singled Out",
    'GD_Challenges.Grenades.Grenade_KillsTransfusionType':                                 "Challenge Grenade: Health Vampire",
    'GD_Challenges.LevelChallenges.Ash_ComDish':                                           "Challenge EridiumBlight: Can You Hear Me Now",
    'GD_Challenges.LevelChallenges.Ash_DestroyTurrets':                                    "Challenge EridiumBlight: Bring Out the Big Guns",
    'GD_Challenges.LevelChallenges.Ash_DonkeyMong':                                        "Challenge EridiumBlight: Tie Clip",
    'GD_Challenges.LevelChallenges.Ash_KingMong':                                          "Challenge EridiumBlight: 'Twas Slag Killed the Beast",
    'GD_Challenges.LevelChallenges.Ash_PipeWalk':                                          "Challenge EridiumBlight: Pipe Dreaming",
    'GD_Challenges.LevelChallenges.Ash_SavetheTurrets':                                    "Challenge EridiumBlight: Save the Turrets",
    'GD_Challenges.LevelChallenges.Ash_VaultRoy':                                          "Challenge EridiumBlight: Cult of the Vault",
    'GD_Challenges.LevelChallenges.Ash_VolcanoClimb':                                      "Challenge EridiumBlight: Vault Hunter vs. The Volcano",
    'GD_Challenges.LevelChallenges.BanditSlaughter_VaultRoy':                              "Challenge Fink's: Cult of the Vault",
    'GD_Challenges.LevelChallenges.BossCliffs_BossKill':                                   "Challenge Bunker: BNK-3R Buster",
    'GD_Challenges.LevelChallenges.BossCliffs_VaultRoy':                                   "Challenge Bunker: Cult of the Vault",
    'GD_Challenges.LevelChallenges.BossVolcano_BossKill':                                  "Challenge VaultOfTheWarrior: The Warrior's Way",
    'GD_Challenges.LevelChallenges.BossVolcano_VaultRoy':                                  "Challenge VaultOfTheWarrior: Cult of the Vault",
    'GD_Challenges.LevelChallenges.BossVolcano_WeaponStash':                               "Challenge VaultOfTheWarrior: Dying of the Light",
    'GD_Challenges.LevelChallenges.Caverns_BossKill':                                      "Challenge CausticCaverns: Harchek's Revenge",
    'GD_Challenges.LevelChallenges.Caverns_GreatHeights':                                  "Challenge CausticCaverns: Ever Blow Bubbles...?",
    'GD_Challenges.LevelChallenges.Caverns_Island':                                        "Challenge CausticCaverns: I Bet I Can Make It",
    'GD_Challenges.LevelChallenges.Caverns_Ooze':                                          "Challenge CausticCaverns: Can't Feel A Thing",
    'GD_Challenges.LevelChallenges.Caverns_VaultRoy':                                      "Challenge CausticCaverns: Cult of the Vault",
    'GD_Challenges.LevelChallenges.Cove_Telescope':                                        "Challenge SouthernShelfBay: I Can See Your Corpse from Here!",
    'GD_Challenges.LevelChallenges.Cove_TightRope':                                        "Challenge SouthernShelfBay: Vault Hunter on Wire",
    'GD_Challenges.LevelChallenges.Cove_VaultRoy':                                         "Challenge SouthernShelfBay: Cult of the Vault",
    'GD_Challenges.LevelChallenges.Cove_Warmong':                                          "Challenge SouthernShelfBay: Midgemong Has No Friends",
    'GD_Challenges.LevelChallenges.Craterlake_Campsite':                                   "Challenge Sawtooth: Happy Camper",
    'GD_Challenges.LevelChallenges.Craterlake_RaceToTop':                                  "Challenge Sawtooth: Race to the Top",
    'GD_Challenges.LevelChallenges.Craterlake_VaultRoy':                                   "Challenge Sawtooth: Cult of the Vault",
    'GD_Challenges.LevelChallenges.CreatureSlaughter_VaultRoy':                            "Challenge NaturalSelectionAnnex: Cult of the Vault",
    'GD_Challenges.LevelChallenges.DamTop_CarKeys':                                        "Challenge BloodshotRamparts: The Last Place You Look",
    'GD_Challenges.LevelChallenges.DamTop_Toll':                                           "Challenge BloodshotRamparts: The Not-So-Phantom Tollbooth",
    'GD_Challenges.LevelChallenges.DamTop_VaultRoy':                                       "Challenge BloodshotRamparts: Cult of the Vault",
    'GD_Challenges.LevelChallenges.Dam_Couch':                                             "Challenge BloodshotStronghold: Eff Yo' Couch",
    'GD_Challenges.LevelChallenges.Dam_SplinterGroup':                                     "Challenge BloodshotStronghold: Cut 'Em No Slack",
    'GD_Challenges.LevelChallenges.Dam_VaultRoy':                                          "Challenge BloodshotStronghold: Cult of the Vault",
    'GD_Challenges.LevelChallenges.Dam_Vortex':                                            "Challenge BloodshotStronghold: Give It a Whirl",
    'GD_Challenges.LevelChallenges.FinalBossAscent_FallenLoader':                          "Challenge HerosPass: When Nature Calls",
    'GD_Challenges.LevelChallenges.FinalBossAscent_LongWallers':                           "Challenge HerosPass: Environmental Protection",
    'GD_Challenges.LevelChallenges.FinalBossAscent_VaultRoy':                              "Challenge HerosPass: Cult of the Vault",
    'GD_Challenges.LevelChallenges.Fridge_BossKill':                                       "Challenge Fridge: Stiff Competition",
    'GD_Challenges.LevelChallenges.Fridge_FrozenRat':                                      "Challenge Fridge: Trapped Rat",
    'GD_Challenges.LevelChallenges.Fridge_LaneyFirst':                                     "Challenge Fridge: Fairest of Them All",
    'GD_Challenges.LevelChallenges.Fridge_LaneyLast':                                      "Challenge Fridge: It's Off to Hell We Go",
    'GD_Challenges.LevelChallenges.Fridge_VaultRoy':                                       "Challenge Fridge: Cult of the Vault",
    'GD_Challenges.LevelChallenges.Frost_Rodeo':                                           "Challenge ThreeHornsValley: This Ain't My First Rodeo",
    'GD_Challenges.LevelChallenges.Frost_VaultRoy':                                        "Challenge ThreeHornsValley: Cult of the Vault",
    'GD_Challenges.LevelChallenges.Fyrestone_Bonehead':                                    "Challenge AridNexusBadlands: Boned",
    'GD_Challenges.LevelChallenges.Fyrestone_DJ':                                          "Challenge AridNexusBoneyard: Dead Air",
    # 'GD_Challenges.LevelChallenges.Fyrestone_FindChest':                                   "Challenge AridNexusBoneyard: Let's Start at the Very Beginning",
    'GD_Challenges.LevelChallenges.Fyrestone_HiddenClaptrap':                              "Challenge AridNexusBadlands: Hey! Over Here!",
    'GD_Challenges.LevelChallenges.Fyrestone_Pipes':                                       "Challenge AridNexusBoneyard: Under Pressure",
    'GD_Challenges.LevelChallenges.Fyrestone_VaultRoy':                                    "Challenge AridNexusBoneyard: Cult of the Vault",
    'GD_Challenges.LevelChallenges.Glacial_VaultRoy':                                      "Challenge WindshearWaste: Cult of the Vault",
    'GD_Challenges.LevelChallenges.GrassCliffs_ActivateRadioTower':                        "Challenge ThousandCuts: Slab UHF",
    'GD_Challenges.LevelChallenges.GrassCliffs_SmashTombstones':                           "Challenge ThousandCuts: A Grave Matter",
    'GD_Challenges.LevelChallenges.GrassCliffs_VaultRoy':                                  "Challenge ThousandCuts: Cult of the Vault",
    'GD_Challenges.LevelChallenges.Grass_FindWindsocks':                                   "Challenge Highlands: Winds of the Highlands",
    'GD_Challenges.LevelChallenges.Grass_HyperionTowers':                                  "Challenge Highlands: Failure to Communicate",
    'GD_Challenges.LevelChallenges.Grass_VaultRoy':                                        "Challenge Highlands: Cult of the Vault",
    'GD_Challenges.LevelChallenges.HypCity_Foreman':                                       "Challenge Opportunity: Shame the Foreman",
    'GD_Challenges.LevelChallenges.HypCity_Rooftops':                                      "Challenge Opportunity: Top o' the World",
    'GD_Challenges.LevelChallenges.HypCity_SecurityCameras':                               "Challenge Opportunity: Down With Big, Handsome Brother",
    'GD_Challenges.LevelChallenges.HypCity_VaultRoy':                                      "Challenge Opportunity: Cult of the Vault",
    'GD_Challenges.LevelChallenges.HypInterlude_GuardTower':                               "Challenge FriendshipGulag: In the Middle of the Night",
    'GD_Challenges.LevelChallenges.HypInterlude_VaultRoy':                                 "Challenge FriendshipGulag: Cult of the Vault",
    'GD_Challenges.LevelChallenges.HypSlaughter_VaultRoy':                                 "Challenge OreChasm: Cult of the Vault",
    'GD_Challenges.LevelChallenges.IceCanyon_LightTotems':                                 "Challenge Frostburn: Totems of Fire",
    'GD_Challenges.LevelChallenges.IceCanyon_ScorchMinions':                               "Challenge Frostburn: Praise Be to Scorch",
    'GD_Challenges.LevelChallenges.IceCanyon_VaultRoy':                                    "Challenge Frostburn: Cult of the Vault",
    'GD_Challenges.LevelChallenges.Ice_SnowSkags':                                         "Challenge ThreeHornsDivide: Man's Best Friends",
    'GD_Challenges.LevelChallenges.Ice_VaultRoy':                                          "Challenge ThreeHornsDivide: Cult of the Vault",
    'GD_Challenges.LevelChallenges.Interlude_CarCrusher':                                  "Challenge Dust: I've Got a Crush on You",
    'GD_Challenges.LevelChallenges.Interlude_Cara-Van':                                    "Challenge Dust: The Van Is Damned",
    'GD_Challenges.LevelChallenges.Interlude_Racetrack':                                   "Challenge Dust: If You're Not First, You're Last",
    'GD_Challenges.LevelChallenges.Interlude_VaultRoy':                                    "Challenge Dust: Cult of the Vault",
    'GD_Challenges.LevelChallenges.Luckys_VaultRoy':                                       "Challenge HolySpirits: Cult of the Vault",
    'GD_Challenges.LevelChallenges.Lynchwood_DeathTrainDuel':                              "Challenge Lynchwood: Duel of Death",
    'GD_Challenges.LevelChallenges.Lynchwood_ExhaustPort':                                 "Challenge Lynchwood: That's Impossible, Even for a Computer",
    'GD_Challenges.LevelChallenges.Lynchwood_SkagRider':                                   "Challenge Lynchwood: Look Ma, No Hands",
    'GD_Challenges.LevelChallenges.Lynchwood_TrainBandit':                                 "Challenge Lynchwood: Last Train to Nowhere",
    'GD_Challenges.LevelChallenges.Lynchwood_VaultRoy':                                    "Challenge Lynchwood: Cult of the Vault",
    'GD_Challenges.LevelChallenges.PandoraPark_Stash':                                     "Challenge WildlifePreserve: Mordy's Secret Stashes",
    'GD_Challenges.LevelChallenges.PandoraPark_Teddy':                                     "Challenge WildlifePreserve: Bear Minimum",
    'GD_Challenges.LevelChallenges.PandoraPark_TumbaPimon':                                "Challenge WildlifePreserve: Ride Together, Die Together",
    'GD_Challenges.LevelChallenges.PandoraPark_VaultRoy':                                  "Challenge WildlifePreserve: Cult of the Vault",
    'GD_Challenges.LevelChallenges.SanctuaryHole_HoleJump':                                "Challenge SanctuaryHole: Down the Rabbit Hole",
    'GD_Challenges.LevelChallenges.SanctuaryHole_SugarShack':                              "Challenge SanctuaryHole: Sugar Shack",
    'GD_Challenges.LevelChallenges.SanctuaryHole_VaultRoy':                                "Challenge SanctuaryHole: Cult of the Vault",
    'GD_Challenges.LevelChallenges.Sanctuary_Jackpot':                                     "Challenge Sanctuary: Jackpot!",
    'GD_Challenges.LevelChallenges.Sanctuary_VaultRoy':                                    "Challenge Sanctuary: Cult of the Vault",
    'GD_Challenges.LevelChallenges.SouthPaw_BossRun':                                      "Challenge Southpaw: Boss Run",
    'GD_Challenges.LevelChallenges.SouthPaw_VaultRoy':                                     "Challenge Southpaw: Cult of the Vault",
    'GD_Challenges.LevelChallenges.SouthernShelf_BoomBoom':                                "Challenge SouthernShelf: Make Boom Go Boom",
    'GD_Challenges.LevelChallenges.SouthernShelf_FlyntFire':                               "Challenge SouthernShelf: Fireproof",
    'GD_Challenges.LevelChallenges.SouthernShelf_VaultRoy':                                "Challenge SouthernShelf: Cult of the Vault",
    'GD_Challenges.LevelChallenges.ThresherRaid_RaidBossKill':                             "Challenge TerramorphousPeak: Terramorphous the Not-So-Invincible",
    'GD_Challenges.LevelChallenges.ThresherRaid_VaultRoy':                                 "Challenge TerramorphousPeak: Cult of the Vault",
    'GD_Challenges.LevelChallenges.TundraExpTrain_VaultRoy':                               "Challenge EndOfTheLine: Cult of the Vault",
    'GD_Challenges.LevelChallenges.TundraExpTrain_Willhelm':                               "Challenge EndOfTheLine: Master of All He Surveys",
    'GD_Challenges.LevelChallenges.TundraExp_MadameVonBartlesby':                          "Challenge TundraExpress: Bug Off",
    'GD_Challenges.LevelChallenges.TundraExpress_MinesDisarm':                             "Challenge TundraExpress: What's Yours Is Mine",
    'GD_Challenges.LevelChallenges.TundraExpress_Reinforcements':                          "Challenge TundraExpress: Positive Reinforcements",
    'GD_Challenges.LevelChallenges.TundraExpress_TopofBuzzardAcademy':                     "Challenge TundraExpress: King of the Buzzard World",
    'GD_Challenges.LevelChallenges.TundraExpress_VaultRoy':                                "Challenge TundraExpress: Cult of the Vault",
    'GD_Challenges.LevelECHOChallenges.MapECHO_AridNexus':                                 "Challenge AridNexusBadlands: The Beginning of the End",
    'GD_Challenges.LevelECHOChallenges.MapECHO_Axton':                                     "Challenge Lynchwood: Do or Die",
    'GD_Challenges.LevelECHOChallenges.MapECHO_Bloodshots':                                "Challenge BloodshotStronghold: Bloodshot Memories",
    'GD_Challenges.LevelECHOChallenges.MapECHO_Dust':                                      "Challenge Dust: Dust to Dust",
    'GD_Challenges.LevelECHOChallenges.MapECHO_Fridge':                                    "Challenge Fridge: The Rakk Knight",
    'GD_Challenges.LevelECHOChallenges.MapECHO_Frostburn':                                 "Challenge Frostburn: Burning Sensation",
    'GD_Challenges.LevelECHOChallenges.MapECHO_Maya':                                      "Challenge WildlifePreserve: Siren's Song",
    'GD_Challenges.LevelECHOChallenges.MapECHO_Opportunity':                               "Challenge Opportunity: Opportunity Knocks",
    'GD_Challenges.LevelECHOChallenges.MapECHO_Sal':                                       "Challenge ThousandCuts: Portrait of the Gunzerker as a Young Man",
    'GD_Challenges.LevelECHOChallenges.MapECHO_Sanctuary':                                 "Challenge Sanctuary: Rise of the Crimson Raiders",
    'GD_Challenges.LevelECHOChallenges.MapECHO_Zero':                                      "Challenge Sawtooth: Haiku Hitman",
    'GD_Challenges.Loot.Loot_OpenChests':                                                  "Challenge Loot: The Call of Booty",
    'GD_Challenges.Loot.Loot_OpenLootables':                                               "Challenge Loot: Open Pandora's Boxes",
    'GD_Challenges.Loot.Loot_PickUpWeapons':                                               "Challenge Loot: Gun Runner",
    'GD_Challenges.Melee.Melee_Kills':                                                     "Challenge Melee: Fisticuffs!",
    'GD_Challenges.Melee.Melee_KillsBladed':                                               "Challenge Melee: A Squall of Violence",
    'GD_Challenges.Miscellaneous.Misc_CompleteChallenges':                                 "Challenge Misc: Yo Dawg, I Heard You Like Challenges",
    'GD_Challenges.Miscellaneous.Misc_JimmyJenkins':                                       "Challenge Misc: JEEEEENKINSSSSSS!!!",
    'GD_Challenges.Miscellaneous.Missions_OptionalObjectivesCompleted':                    "Challenge Misc: Compl33tionist",
    'GD_Challenges.Miscellaneous.Missions_SideMissionsCompleted':                          "Challenge Misc: Sidejacked",
    'GD_Challenges.Pickups.Inventory_PickupBlueItems':                                     "Challenge Loot: I Like My Treasure Rare",
    'GD_Challenges.Pickups.Inventory_PickupGreenItems':                                    "Challenge Loot: It's Not Easy Looting Green",
    'GD_Challenges.Pickups.Inventory_PickupOrangeItems':                                   "Challenge Loot: Nothing Rhymes with Orange",
    'GD_Challenges.Pickups.Inventory_PickupPurpleItems':                                   "Challenge Loot: Purple Reign",
    'GD_Challenges.Pickups.Inventory_PickupWhiteItems':                                    "Challenge Loot: Another Man's Treasure",
    'GD_Challenges.Player.Player_CoopRevivesOfFriends':                                    "Challenge Recovery: This Is No Time for Lazy!",
    'GD_Challenges.Player.Player_PointsHealed':                                            "Challenge Recovery: Heal Plz",
    'GD_Challenges.Player.Player_SecondWind':                                              "Challenge Recovery: I'll Just Help Myself",
    'GD_Challenges.Player.Player_SecondWindFromBadass':                                    "Challenge Recovery: Badass Bingo",
    'GD_Challenges.Player.Player_SecondWindFromCorrosive':                                 "Challenge Recovery: Green Meanie",
    'GD_Challenges.Player.Player_SecondWindFromFire':                                      "Challenge Recovery: Death, Wind, and Fire",
    'GD_Challenges.Player.Player_SecondWindFromShock':                                     "Challenge Recovery: I'm Back! Shocked?",
    'GD_Challenges.Shields.Shields_AbsorbAmmo':                                            "Challenge Shields: Ammo Eater",
    'GD_Challenges.Shields.Shields_KillsImpact':                                           "Challenge Shields: Amp It Up",
    'GD_Challenges.Shields.Shields_KillsNova':                                             "Challenge Shields: Super Novas",
    'GD_Challenges.Shields.Shields_KillsRoid':                                             "Challenge Shields: Roid Rage",
    'GD_Challenges.Shields.Shields_KillsSpikes':                                           "Challenge Shields: Game of Thorns",
    'GD_Challenges.Vehicles.Vehicles_KillByPowerSlide':                                    "Challenge Vehicles: Blue Sparks",
    'GD_Challenges.Vehicles.Vehicles_KillByRamming':                                       "Challenge Vehicles: Hit-and-Fun",
    'GD_Challenges.Vehicles.Vehicles_KillsWhilePassenger':                                 "Challenge Vehicles: Passive Aggressive",
    'GD_Challenges.Vehicles.Vehicles_KillsWithVehicleWeapon':                              "Challenge Vehicles: Turret Syndrome",
    'GD_Challenges.Vehicles.Vehicles_VehicleKillsVehicle':                                 "Challenge Vehicles: One Van Leaves",
    'GD_Challenges.Weapons.AssaultRifle_CriticalHitKills':                                 "Challenge AssaultRifle: ...This Is My Gun",
    'GD_Challenges.Weapons.AssaultRifle_CriticalHits':                                     "Challenge AssaultRifle: This Is My Rifle...",
    'GD_Challenges.Weapons.AssaultRifle_Kills':                                            "Challenge AssaultRifle: Aggravated Assault",
    'GD_Challenges.Weapons.AssaultRifle_KillsCrouched':                                    "Challenge AssaultRifle: Crouching Tiger, Hidden Assault Rifle",
    'GD_Challenges.Weapons.AssaultRifle_SecondWinds':                                      "Challenge AssaultRifle: From My Cold, Dead Hands",
    'GD_Challenges.Weapons.Launcher_Kills':                                                "Challenge Launcher: Rocket and Roll",
    'GD_Challenges.Weapons.Launcher_KillsDirectHit':                                       "Challenge Launcher: Catch-a-Rocket!",
    'GD_Challenges.Weapons.Launcher_KillsFullShieldEnemy':                                 "Challenge Launcher: Shield Basher",
    'GD_Challenges.Weapons.Launcher_KillsLongRange':                                       "Challenge Launcher: Sky Rockets in Flight...",
    'GD_Challenges.Weapons.Launcher_KillsSplashDamage':                                    "Challenge Launcher: Splish Splash",
    'GD_Challenges.Weapons.Launcher_SecondWinds':                                          "Challenge Launcher: Gone with the Second Wind",
    'GD_Challenges.Weapons.Pistol_CriticalHitKills':                                       "Challenge Pistol: Pistolero",
    'GD_Challenges.Weapons.Pistol_CriticalHits':                                           "Challenge Pistol: Deadeye",
    'GD_Challenges.Weapons.Pistol_Kills':                                                  "Challenge Pistol: The Killer",
    'GD_Challenges.Weapons.Pistol_KillsQuickshot':                                         "Challenge Pistol: Quickdraw",
    'GD_Challenges.Weapons.Pistol_SecondWinds':                                            "Challenge Pistol: Hard Boiled",
    'GD_Challenges.Weapons.SMG_CriticalHitKills':                                          "Challenge SMG: High Rate of Ire",
    'GD_Challenges.Weapons.SMG_CriticalHits':                                              "Challenge SMG: Constructive Criticism",
    'GD_Challenges.Weapons.SMG_Kills':                                                     "Challenge SMG: Hail of Bullets",
    'GD_Challenges.Weapons.SMG_SecondWinds':                                               "Challenge SMG: More Like Submachine FUN",
    'GD_Challenges.Weapons.Shotgun_CriticalHitKills':                                      "Challenge Shotgun: Shotgun Surgeon",
    'GD_Challenges.Weapons.Shotgun_CriticalHits':                                          "Challenge Shotgun: Faceful of Buckshot",
    'GD_Challenges.Weapons.Shotgun_Kills':                                                 "Challenge Shotgun: Shotgun!",
    'GD_Challenges.Weapons.Shotgun_KillsLongRange':                                        "Challenge Shotgun: Shotgun Sniper",
    'GD_Challenges.Weapons.Shotgun_KillsPointBlank':                                       "Challenge Shotgun: Open Wide!",
    'GD_Challenges.Weapons.Shotgun_SecondWinds':                                           "Challenge Shotgun: Lock, Stock, and...",
    'GD_Challenges.Weapons.SniperRifle_Kills':                                             "Challenge Sniper: Longshot",
    'GD_Challenges.Weapons.SniperRifle_KillsFromHip':                                      "Challenge Sniper: No Scope, No Problem",
    'GD_Challenges.Weapons.SniperRifle_KillsFullShieldEnemy':                              "Challenge Sniper: Eviscerated",
    'GD_Challenges.Weapons.SniperRifle_KillsUnaware':                                      "Challenge Sniper: Surprise!",
    'GD_Challenges.Weapons.Sniper_CriticalHitKills':                                       "Challenge Sniper: Snipe Hunting",
    'GD_Challenges.Weapons.Sniper_CriticalHits':                                           "Challenge Sniper: Longshot Headshot",
    'GD_Challenges.Weapons.Sniper_SecondWinds':                                            "Challenge Sniper: Leaf on the Second Wind",
    'GD_Challenges.elemental.Elemental_DealBonusSlagDamage':                               "Challenge Elemental: Slag-Licked",
    'GD_Challenges.elemental.Elemental_DealCorrosiveDOTDamage':                            "Challenge Elemental: Corroderate",
    'GD_Challenges.elemental.Elemental_DealFireDOTDamage':                                 "Challenge Elemental: I Just Want to Set the World on Fire",
    'GD_Challenges.elemental.Elemental_DealShockDOTDamage':                                "Challenge Elemental: Say ''Watt'' Again",
    'GD_Challenges.elemental.Elemental_KillEnemiesCorrosive':                              "Challenge Elemental: Acid Trip",
    'GD_Challenges.elemental.Elemental_KillEnemiesExplosive':                              "Challenge Elemental: Boom.",
    'GD_Challenges.elemental.Elemental_SetEnemiesOnFire':                                  "Challenge Elemental: Cowering Inferno",
    'GD_Challenges.enemies.Enemies_KillBruisers':                                          "Challenge Enemies: Cruising for a Bruising",
    'GD_Challenges.enemies.Enemies_KillBullymongs':                                        "Challenge Enemies: Bully the Bullies",
    'GD_Challenges.enemies.Enemies_KillConstructors':                                      "Challenge Enemies: Constructor Destructor",
    'GD_Challenges.enemies.Enemies_KillCrystalisks':                                       "Challenge Enemies: Crystals Are a Girl's Best Friend",
    'GD_Challenges.enemies.Enemies_KillEngineers':                                         "Challenge Enemies: Paingineering",
    'GD_Challenges.enemies.Enemies_KillGoliaths':                                          "Challenge Enemies: WHY SO MUCH HURT?!",
    'GD_Challenges.enemies.Enemies_KillGyros':                                             "Challenge Enemies: Die in the Friendly Skies",
    'GD_Challenges.enemies.Enemies_KillLoaders':                                           "Challenge Enemies: Load and Lock",
    'GD_Challenges.enemies.Enemies_KillMarauders':                                         "Challenge Enemies: Marauder? I Hardly Know 'Er!",
    'GD_Challenges.enemies.Enemies_KillMidgets':                                           "Challenge Enemies: Little Person, Big Pain",
    'GD_Challenges.enemies.Enemies_KillNomads':                                            "Challenge Enemies: You (No)Mad, Bro?",
    'GD_Challenges.enemies.Enemies_KillPsychos':                                           "Challenge Enemies: Mama's Boys",
    'GD_Challenges.enemies.Enemies_KillRats':                                              "Challenge Enemies: You Dirty Rat",
    'GD_Challenges.enemies.Enemies_KillSkags':                                             "Challenge Enemies: Skags to Riches",
    'GD_Challenges.enemies.Enemies_KillSpiderants':                                        "Challenge Enemies: Pest Control",
    'GD_Challenges.enemies.Enemies_KillStalkers':                                          "Challenge Enemies: You're One Ugly Mother...",
    'GD_Challenges.enemies.Enemies_KillSurveyors':                                         "Challenge Enemies: Just a Moment of Your Time...",
    'GD_Challenges.enemies.Enemies_KillThreshers':                                         "Challenge Enemies: Tentacle Obsession",
    'GD_Challenges.enemies.Enemies_KillVarkid':                                            "Challenge Enemies: Another Bug Hunt",
    'GD_Challenges.enemies.Enemies_KillVarkidPods':                                        "Challenge Enemies: Pod Pew Pew",
    'GD_Challenges.enemies.Enemies_ReleaseChainedMidgets':                                 "Challenge Enemies: Short-Chained",
    'GD_Challenges.enemies.Enemies_ShootBullymongProjectiles':                             "Challenge Enemies: Hurly Burly",
    'GD_Iris_Challenges.Challenges.Challenge_Iris_BuyTorgueItems':                         "Challenge TorgueDLC: Torgue Items Purchased",
    'GD_Iris_Challenges.Challenges.Challenge_Iris_CompleteBattles':                        "Challenge TorgueDLC: Battles Completed",
    'GD_Iris_Challenges.Challenges.Challenge_Iris_KillBikers':                             "Challenge TorgueDLC: Bikers Killed",
    'GD_Iris_Challenges.Challenges.Challenge_Iris_KillMotorcycles':                        "Challenge TorgueDLC: Bikes Destroyed",
    'GD_Iris_Challenges.Challenges.Challenge_Iris_Raid1':                                  "Challenge TorgueDLC: Pete the Invincible Defeated",
    'GD_Iris_Challenges.Challenges.Challenge_Iris_TorgueTokens':                           "Challenge TorgueDLC: Torgue Tokens Acquired",
    'GD_Iris_Challenges.LevelChallenges.Arena_C4IsForCookie':                              "Challenge TorgueArena: C4 Is For Cookie",
    'GD_Iris_Challenges.LevelChallenges.Arena_CultOfTheVault':                             "Challenge TorgueArena: Cult of the Vault",
    'GD_Iris_Challenges.LevelChallenges.Arena_ItsCool':                                    "Challenge TorgueArena: It's Cool, I'm Part of the Crew",
    'GD_Iris_Challenges.LevelChallenges.Arena_NotEntertained':                             "Challenge TorgueArena: Are You Not Entertained?",
    'GD_Iris_Challenges.LevelChallenges.Arena_RingOfFire':                                 "Challenge TorgueArena: Burnin' Ring of Fire",
    'GD_Iris_Challenges.LevelChallenges.Beatdown_CultOfTheVault':                          "Challenge Beatdown: Cult of the Vault",
    'GD_Iris_Challenges.LevelChallenges.Beatdown_IThoughtBigger':                          "Challenge Beatdown: I Thought You'd Be... Bigger",
    'GD_Iris_Challenges.LevelChallenges.Crater_AsAdvertised':                              "Challenge BadassCrater: As Advertised",
    'GD_Iris_Challenges.LevelChallenges.Crater_CultOfTheVault':                            "Challenge BadassCrater: Cult of the Vault",
    'GD_Iris_Challenges.LevelChallenges.Crater_FanclubMembership':                         "Challenge BadassCrater: Fan Club Membership",
    'GD_Iris_Challenges.LevelChallenges.Crater_ICanFly':                                   "Challenge BadassCrater: I Can Fly!",
    'GD_Iris_Challenges.LevelChallenges.Crater_OnlyShellsINeed':                           "Challenge BadassCrater: Only Shells I Need Are in My Guns",
    'GD_Iris_Challenges.LevelChallenges.Forge_AirMail':                                    "Challenge Forge: Air Mail",
    'GD_Iris_Challenges.LevelChallenges.Forge_CultOfTheVault':                             "Challenge Forge: Cult of the Vault",
    'GD_Iris_Challenges.LevelChallenges.Forge_IDIDStartFire':                              "Challenge Forge: I DID Start the Fire",
    'GD_Iris_Challenges.LevelChallenges.Forge_ParachutePansies':                           "Challenge Forge: Parachutes Are for Pansies",
    'GD_Iris_Challenges.LevelChallenges.Southern_CultOfTheVault':                          "Challenge SouthernRaceway: Cult of the Vault",
    'GD_Orchid_Challenges.Challenges.Challenge_Orchid_Crystals':                           "Challenge ScarlettDLC: In The Pink",
    'GD_Orchid_Challenges.Challenges.Challenge_Orchid_KillBandits':                        "Challenge ScarlettDLC: Land Lubber",
    'GD_Orchid_Challenges.Challenges.Challenge_Orchid_KillHovercrafts':                    "Challenge ScarlettDLC: Hovernator",
    'GD_Orchid_Challenges.Challenges.Challenge_Orchid_KillWorms':                          "Challenge ScarlettDLC: Worm Killer",
    'GD_Orchid_Challenges.Challenges.Challenge_Orchid_PirateChests':                       "Challenge ScarlettDLC: Pirate Booty",
    'GD_Orchid_Challenges.Challenges.Challenge_Orchid_Purchase':                           "Challenge ScarlettDLC: Shady Dealings",
    'GD_Orchid_Challenges.Challenges.Challenge_Orchid_Raid1':                              "Challenge ScarlettDLC: Hyperius the Not-So-Invincible",
    'GD_Orchid_Challenges.Challenges.Challenge_Orchid_Raid3':                              "Challenge ScarlettDLC: Master Worm Food",
    'GD_Orchid_Challenges.LevelChallenges.Caves_BossKill':                                 "Challenge HaytersFolly: Playing Chicken in my Sleep",
    'GD_Orchid_Challenges.LevelChallenges.Caves_SecretStash':                              "Challenge HaytersFolly: Wet Reward",
    'GD_Orchid_Challenges.LevelChallenges.Caves_Telescope':                                "Challenge HaytersFolly: Master of My Domain",
    'GD_Orchid_Challenges.LevelChallenges.Caves_VaultRoy':                                 "Challenge HaytersFolly: Cult of the Vault",
    'GD_Orchid_Challenges.LevelChallenges.OasisTown_RooftopChests':                        "Challenge Oasis: I Ain't Afraid of Heights",
    'GD_Orchid_Challenges.LevelChallenges.OasisTown_VaultRoy':                             "Challenge Oasis: Cult of the Vault",
    'GD_Orchid_Challenges.LevelChallenges.OasisTown_Wurmtail':                             "Challenge Oasis: Horrid's Hideaway",
    'GD_Orchid_Challenges.LevelChallenges.Refinery_FindThings':                            "Challenge Washburne: I Get It for the Articles",
    'GD_Orchid_Challenges.LevelChallenges.Refinery_SecretStash':                           "Challenge Washburne: Arm Thyself",
    'GD_Orchid_Challenges.LevelChallenges.Refinery_VaultRoy':                              "Challenge Washburne: Cult of the Vault",
    'GD_Orchid_Challenges.LevelChallenges.RockSpire_SecretStash':                          "Challenge Magnys Lighthouse: Maroonie's Inheritance",
    'GD_Orchid_Challenges.LevelChallenges.RockSpire_UseTurret':                            "Challenge Magnys Lighthouse: N00b Cannon",
    'GD_Orchid_Challenges.LevelChallenges.RockSpire_VaultRoy':                             "Challenge Magnys Lighthouse: Cult of the Vault",
    'GD_Orchid_Challenges.LevelChallenges.SaltFlats_KillHovercraft':                       "Challenge Wurmwater: Skiffless",
    'GD_Orchid_Challenges.LevelChallenges.SaltFlats_RaidCaravan':                          "Challenge Wurmwater: Comb the Desert!",
    'GD_Orchid_Challenges.LevelChallenges.SaltFlats_RefinerySecret':                       "Challenge Wurmwater: Refined Tastes",
    'GD_Orchid_Challenges.LevelChallenges.SaltFlats_VaultRoy':                             "Challenge Wurmwater: Cult of the Vault",
    'GD_Orchid_Challenges.LevelChallenges.ShipGraveyard_FindDolls':                        "Challenge Rustyards: My Main Squeeze",
    'GD_Orchid_Challenges.LevelChallenges.ShipGraveyard_Mast':                             "Challenge Rustyards: Crow's Nest",
    'GD_Orchid_Challenges.LevelChallenges.ShipGraveyard_VaultRoy':                         "Challenge Rustyards: Cult of the Vault",
    'GD_Orchid_Challenges.LevelChallenges.WormBelly_SecretStash':                          "Challenge LeviathansLair: Lost Lost Treasure",
    'GD_Orchid_Challenges.LevelChallenges.WormBelly_TimedFight':                           "Challenge LeviathansLair: Bleeding Scarlett",
    'GD_Orchid_Challenges.LevelChallenges.WormBelly_VaultRoy':                             "Challenge LeviathansLair: Cult of the Vault",
    'GD_Sage_Challenges.Challenges.Challenge_Sage_KillBoroks':                             "Challenge HammerlockDLC: Boroking Around",
    'GD_Sage_Challenges.Challenges.Challenge_Sage_KillDrifters':                           "Challenge HammerlockDLC: Harder They Fall",
    'GD_Sage_Challenges.Challenges.Challenge_Sage_KillFanBoats':                           "Challenge HammerlockDLC: Fan Boy",
    'GD_Sage_Challenges.Challenges.Challenge_Sage_KillSavages':                            "Challenge HammerlockDLC: Savage Bloody Savage",
    'GD_Sage_Challenges.Challenges.Challenge_Sage_KillScaylions':                          "Challenge HammerlockDLC: Stinging Sensation",
    'GD_Sage_Challenges.Challenges.Challenge_Sage_RaidBossA':                              "Challenge HammerlockDLC: Voracidous the Invincible",
    'GD_Sage_Challenges.LevelChallenges.CavesCliffs_CageFree':                             "Challenge CandlerakksCrag: Cage Free",
    'GD_Sage_Challenges.LevelChallenges.CavesCliffs_NestEgg':                              "Challenge CandlerakksCrag: Nest Egg",
    'GD_Sage_Challenges.LevelChallenges.CavesCliffs_VaultRoy':                             "Challenge CandlerakksCrag: Cult of the Vault",
    'GD_Sage_Challenges.LevelChallenges.HyperionShip_VaultRoy':                            "Challenge Terminus: Cult of the Vault",
    'GD_Sage_Challenges.LevelChallenges.PowerStation_Horrible':                            "Challenge Ardorton Station: Horrible Assistants",
    'GD_Sage_Challenges.LevelChallenges.PowerStation_KillYouLast':                         "Challenge Ardorton Station: I Promised to Kill You Last",
    'GD_Sage_Challenges.LevelChallenges.PowerStation_PowerHigh':                           "Challenge Ardorton Station: Power High",
    'GD_Sage_Challenges.LevelChallenges.PowerStation_VaultRoy':                            "Challenge Ardorton Station: Cult of the Vault",
    'GD_Sage_Challenges.LevelChallenges.RockForest_Clap':                                  "Challenge ScyllasGrove: Beware the Clap",
    'GD_Sage_Challenges.LevelChallenges.RockForest_HumanBBQ':                              "Challenge ScyllasGrove: Human Barbecue",
    'GD_Sage_Challenges.LevelChallenges.RockForest_RakkForest':                            "Challenge ScyllasGrove: Rakk Forest",
    'GD_Sage_Challenges.LevelChallenges.RockForest_VaultRoy':                              "Challenge ScyllasGrove: Cult of the Vault",
    'GD_Sage_Challenges.LevelChallenges.Underground_Fishing':                              "Challenge HuntersGrotto: Grenade Fishing",
    'GD_Sage_Challenges.LevelChallenges.Underground_Stool':                                "Challenge HuntersGrotto: Stool Sample",
    'GD_Sage_Challenges.LevelChallenges.Underground_Traps':                                "Challenge HuntersGrotto: It's a Trap! Kind of.",
    'GD_Sage_Challenges.LevelChallenges.Underground_VaultRoy':                             "Challenge HuntersGrotto: Cult of the Vault",
    # 'GD_Challenges.LevelChallenges.Cove_Skipping':                                         "Cove_Skipping: Hustle from Flow",
    # 'GD_Orchid_Challenges.LevelChallenges.SaltFlats_HovercraftLand':                       "SaltFlats_HovercraftLand: Buccaneer's Big Jump",
    # 'Sage_Prop_Cliffs.Caves_Telescope':                                                    "Caves_Telescope: Master of My Domain",
    # 'GD_Aster_Challenges.LevelChallenges.CastleExterior_DragonBoss':                       "CastleExterior_DragonBoss: Stand Your Ground",
    # 'GD_Aster_Challenges.LevelChallenges.DeadForest_Grave':                                "DeadForest_Grave: Put to Rest",
}

annoying_challenges = [
    "GD_Challenges.Weapons.Launcher_KillsDirectHit",
    "GD_Challenges.Weapons.Shotgun_KillsLongRange",
]

def reveal_annoying_challenges():
    print("reveal_annoying_challenges")
    for chal_name in annoying_challenges:
        try:
            chal = unrealsdk.find_object("ChallengeDefinition", chal_name)
            get_pc().ReceiveChallenge(ChalDef=chal)
        except ValueError:
            pass
