# These use the nicely formatted names
# TODO: potentially only need one per entrance. Not sure if they are all the right way round though
entrance_to_req_areas = {
    # LevelTravelStationDefinition
    "BackburnerToOldDust":                     ["Dahl Abandon", "The Backburner"],
    # "BackburnerToSanctIntro":                [], #["The Backburner", "FFS Intro Sanctuary"],
    "HeliosToSandwormCavern":                  ["Helios Fallen", "The Burrows"],
    "OldDustToBackburner":                     ["The Backburner", "Dahl Abandon"],
    "OldDustToResearchCenter":                 ["Dahl Abandon", "Mt. Scarab Research Center"],
    "OldDustToSandwormCavern":                 ["Dahl Abandon", "The Burrows"],
    "RaidBossToSandwormCavern":                ["Writhing Deep", "The Burrows"],
    "ResearchCenterToOldDust":                 ["Dahl Abandon", "Mt. Scarab Research Center"],
    "ResearchCenterToSanctuary":               ["Mt. Scarab Research Center", "FFS Boss Fight"],
    # "SanctIntroToBackburner":                [], # ["FFS Intro Sanctuary", "The Backburner"],
    "SanctuaryToResearchCenter":               ["Mt. Scarab Research Center", ],
    "SandwormCavernToHelios":                  ["The Burrows", "Helios Fallen"],
    "SandwormCavernToOldDust":                 ["Dahl Abandon", "The Burrows"],
    "SandwormCavernToRaidBoss":                ["Writhing Deep", "The Burrows"],
    # "CastleExteriorToCastleKeepFake":        ["Hatred's Shadow", "Dragon Keep"],
    "CastleExteriorToDungeon":                 ["Lair of Infinite Agony", "Hatred's Shadow"],
    # "CastleExteriorToDungeons":              ["Hatred's Shadow", "Lair of Infinite Agony"],
    "CastleExteriorToMines":                   ["Hatred's Shadow", "Mines of Avarice"],
    # "CastleKeepToCastleExteriorFake":        ["Hatred's Shadow", "Dragon Keep"],
    "CastleKeepToDungeon":                     ["Dragon Keep", "Lair of Infinite Agony"],
    # "CastleKeepToDungeons":                  ["Dragon Keep", "Lair of Infinite Agony"],
    "DarkForestToDeadForest":                  ["The Forest", "Immortal Woods"],
    # "DarkForestToMines":                     ["The Forest", "Mines of Avarice"],
    "DarkForestToVillage":                     ["The Forest", "Flamerock Refuge"],
    "DeadForestToDarkForest":                  ["Immortal Woods", "The Forest"],
    "DeadForestToMines":                       ["Mines of Avarice", "Immortal Woods"],
    "DocksToVillage":                          ["Flamerock Refuge", "Unassuming Docks"],
    "DungeonRaidToDungeon":                    ["Lair of Infinite Agony", "The Winged Storm"],
    # "DungeonRaidToDungeons":                 ["Lair of Infinite Agony", "The Winged Storm"],
    # "DungeonsToCastleExterior":              ["Hatred's Shadow", "Lair of Infinite Agony"],
    # "DungeonsToCastleKeep":                  ["Lair of Infinite Agony", "Dragon Keep"],
    # "DungeonsToDungeonRaid":                 ["Lair of Infinite Agony", "The Winged Storm"],
    "DungeonToCastleExterior":                 ["Hatred's Shadow", "Lair of Infinite Agony"],
    "DungeonToCastleKeep":                     ["Dragon Keep", "Lair of Infinite Agony"],
    "DungeonToDungeonRaid":                    ["The Winged Storm", "Lair of Infinite Agony"],
    "MinesToCastleExterior":                   ["Mines of Avarice", "Hatred's Shadow"],
    # "MinesToDarkForest":                     ["The Forest", "Mines of Avarice"],
    "MinesToDeadForest":                       ["Immortal Woods", "Mines of Avarice"],
    "TempleOfSlaughterToVillage":              ["Flamerock Refuge", "Murderlin's Temple"],
    "VillageToDarkForest":                     ["The Forest", "Flamerock Refuge"],
    "VillageToDocks":                          ["Flamerock Refuge", "Unassuming Docks"],
    # "VillageToMines":                        ["Flamerock Refuge", "Mines of Avarice"],
    "VillageToTempleOfSlaughter":              ["Murderlin's Temple", "Flamerock Refuge"],
    "BeatdowntoPyroPeats":                     ["Pyro Pete's Bar", "The Beatdown"],
    "BeatdowntoPyroPetes2":                    ["Pyro Pete's Bar", "The Beatdown"],
    # "CraterToKickedOut":                     [],
    "ArenaTASToCrater":                        ["Badass Crater", "Torgue Arena"],
    "ArenaToCrater":                           ["Badass Crater", "Torgue Arena"],
    "BackdoorToCrater":                        ["Badass Crater", "Torgue Arena"],
    "BeatdownToCrater":                        ["The Beatdown", "Badass Crater"],
    "ForgeToCrater":                           ["The Forge", "Badass Crater"],
    "CraterToArena":                           ["Torgue Arena", "Badass Crater"],
    "CraterToArenaTAS":                        ["Torgue Arena", "Badass Crater"],
    "CraterToBackdoor":                        ["Torgue Arena", "Badass Crater"],
    "CraterToBeatdown":                        ["The Beatdown", "Badass Crater"],
    "CraterToForge":                           ["The Forge", "Badass Crater"],
    "CraterToMamma":                           ["Southern Raceway", "Badass Crater"],
    "CraterToMoxxi":                           ["Badass Crater" "Badass Crater Bar"],
    "MammaToCrater":                           ["Badass Crater", "Southern Raceway"],
    "MoxxiToCrater":                           ["Badass Crater Bar", "Badass Crater"],
    # "KickedOutToCrater":                     ["Badass Crater"],
    "PyroPetesToBeatdown":                     ["Pyro Pete's Bar", "The Beatdown"],
    # "PyroPetesToBeatdown2":                  ["Pyro Pete's Bar", "The Beatdown"],
    "PyroPeteToBeatdown":                      ["Pyro Pete's Bar", "The Beatdown"],
    "PyroPetetoBeatdown2":                     ["Pyro Pete's Bar", "The Beatdown"],
    "AridNexusToStockade":                     ["Arid Nexus Badlands", "Arid Nexus Boneyard"],
    "AshToVolcano":                            ["Vault of the Warrior", "Eridium Blight"],
    "FrostToIce":                              ["Three Horns Divide", "Three Horns Valley"],
    "FrostToIce2":                             ["Three Horns Divide", "Three Horns Valley"],
    "GrassRoadToOutwash":                      ["Highlands Outwash", "Highlands"],
    "IcetoFrost":                              ["Three Horns Valley", "Three Horns Divide"],
    "IceToFrost2":                             ["Three Horns Valley", "Three Horns Divide"],
    "HypInterToInterlude":                     ["The Dust", "Friendship Gulag"],
    "InterludeToAsh":                          ["Eridium Blight", "The Dust"],
    # "InterludeToDamTop":                     ["The Dust", "Bloodshot Ramparts"], # !?
    # "InterludeToDLC":                        ["The Dust"], # ???
    "InterludeToGrass":                        ["Highlands", "The Dust"],
    "InterludeToHypInter":                     ["Friendship Gulag", "The Dust"],
    "InterludeToIce":                          ["The Dust", "Three Horns Divide"],
    "InterludeToLynchwood":                    ["Lynchwood", "The Dust"],
    "LynchwoodToInterlude":                    ["The Dust", "Lynchwood"],
    "OutwashToFridge":                         ["Highlands Outwash", "The Fridge"],
    "OutwashToGrass":                          ["Highlands", "Highlands Outwash"],
    "OutwashToGrassRoad":                      ["Highlands", "Highlands Outwash"],
    "StockadeToAridNexus":                     ["Arid Nexus Boneyard", "Arid Nexus Badlands"],
    "TundraExpressToWilhelm":                  ["End of the Line", "Tundra Express"],
    # "VolcanoToAsh":                          ["Eridium Blight", "Vault of the Warrior"],
    "WilhelmToTundraExpress":                  ["Tundra Express", "End of the Line"],
    "CavernsToSanctuaryHole":                  ["Caustic Caverns", "Sanctuary Hole"],
    "CoveToWaterfront":                        ["Southern Shelf Bay", "Southern Shelf"],
    "DamToDamTop":                             ["Bloodshot Ramparts", "Bloodshot Stronghold"],
    "DamToIce":                                ["Three Horns Valley", "Bloodshot Stronghold"],
    "DamTopToDam":                             ["Bloodshot Stronghold", "Bloodshot Ramparts"],
    # "DamTopToInterlude":                     ["Bloodshot Ramparts", "The Dust"], # ???
    "GlacialToWaterfront":                     ["Southern Shelf"],
    "IceCanyonToIce":                          ["Three Horns Divide", "Frostburn Canyon"],
    "IceToDam":                                ["Bloodshot Stronghold", "Three Horns Valley"],
    "IceToFridge":                             ["The Fridge", "Three Horns Valley"],
    "IceToIceCanyon":                          ["Frostburn Canyon", "Three Horns Divide"],
    "IceToInterlude":                          ["The Dust", "Three Horns Valley"],
    "IceToSanctuary":                          ["Sanctuary", "Three Horns Divide"],
    "IceToSanctuaryHole":                      ["Sanctuary Hole", "Three Horns Divide"],
    "IceToSouthpawFactory":                    ["Southpaw Steam & Power", "Three Horns Valley"],
    "IceToTundraExpress":                      ["Tundra Express", "Three Horns Divide"],
    "IceToWaterfront":                         ["Three Horns Divide", "Southern Shelf"],
    "SanctuaryHoleToCaverns":                  ["Caustic Caverns", "Sanctuary Hole"],
    "SanctuaryHoleToIce":                      ["Sanctuary Hole", "Three Horns Divide"],
    "SanctuaryToIce":                          ["Sanctuary", "Three Horns Divide"],
    # "SanctuaryToVOGsChamber":                ["Sanctuary"],
    "SouthpawFactoryToIce":                    ["Southpaw Steam & Power", "Three Horns Valley"],
    "TundraExpressToIce":                      ["Tundra Express", "Three Horns Divide"],
    # "WaterfrontDocksToIce":                  ["Southern Shelf", "Three Horns Divide"],
    "WaterfrontToCove":                        ["Southern Shelf", "Southern Shelf Bay"],
    "WaterfrontToGlacial":                     ["Southern Shelf"],
    "WaterfrontToIce":                         ["Three Horns Divide", "Southern Shelf"],
    "BanditSlaughterToFridge":                 ["The Fridge", "Fink's Slaughterhouse"],
    "BossCliffsToCliffs":                      ["The Bunker", "Thousand Cuts"],
    "BossCliffsToVOGsChamber":                 ["Control Core Angel", "The Bunker"],
    "CliffsToBossCliffs":                      ["Thousand Cuts", "The Bunker"],
    "CliffsToGrass":                           ["Thousand Cuts", "Highlands"],
    "CliffsToThresherRaid":                    ["Terramorphous Peak", "Thousand Cuts"],
    "CreatureSlaughterToPandoraPark":          ["Natural Selection Annex", "Wildlife Exploitation Preserve"],
    "FridgeToBanditSlaughter":                 ["Fink's Slaughterhouse", "The Fridge"],
    "FridgeToGrass":                           ["Highlands", "The Fridge"],
    "FridgeToIce":                             ["The Fridge", "Three Horns Valley"],
    "GrassToCliffs":                           ["Thousand Cuts", "Highlands"],
    "GrassToFridge":                           ["Highlands", "The Fridge"], # this isn't real?
    "GrassToHyperionCity":                     ["Opportunity", "Highlands"],
    "GrassToInterlude":                        ["The Dust", "Highlands"],
    "GrassToLuckys":                           ["The Holy Spirits", "Highlands"],
    "GrassToPandoraPark":                      ["Wildlife Exploitation Preserve", "Highlands"],
    "HyperionCityToGrass":                     ["Highlands", "Opportunity"],
    "LuckysToGrass":                           ["Highlands", "The Holy Spirits"],
    "PandoraParkToCreatureSlaughter":          ["Natural Selection Annex", "Wildlife Exploitation Preserve"],
    "PandoraParkToGrass":                      ["Wildlife Exploitation Preserve", "Highlands"],
    "ThresherRaidToCliffs":                    ["Thousand Cuts", "Terramorphous Peak"],
    "VOGsChamberToBossCliffs":                 ["The Bunker", "Control Core Angel"],
    # "VOGsChamberToSanctuary":                ["Control Core Angel"],
    "AshToCraterLake":                         ["Sawtooth Cauldron", "Eridium Blight"],
    "AshToFinalBossAscent":                    ["Hero's Pass", "Eridium Blight"],
    "AshToFyrestone":                          ["Arid Nexus Boneyard", "Eridium Blight"],
    "AshToInterlude":                          ["Eridium Blight", "The Dust"],
    "AshToRobotSlaughter":                     ["Ore Chasm", "Eridium Blight"],
    "CraterLakeToAsh":                         ["Eridium Blight", "Sawtooth Cauldron"],
    "FinalBossAscentToAsh":                    ["Eridium Blight", "Hero's Pass"],
    "FinalBossAscentToVolcano":                ["Vault of the Warrior", "Hero's Pass"],
    "FyrestoneToAsh":                          ["Eridium Blight", "Arid Nexus Boneyard"],
    "RobotSlaughterToAsh":                     ["Eridium Blight", "Ore Chasm"],
    "VolcanoToFinalBossAscent":                ["Hero's Pass","Vault of the Warrior"],
    "CavesToOasisTown":                        ["Oasis", "Hayter's Folly"],
    "OasisTownToCaves":                        ["Hayter's Folly", "Oasis"],
    "OasisTownToSaltFlats":                    ["Oasis","Wurmwater"],
    # "OasisTownToSpire":                      ["Oasis", "Magnys Lighthouse"],
    "OasisTownToWormBelly":                    ["Oasis", "The Leviathan's Lair"],
    "RefineryToSaltFlats":                     ["Wurmwater", "Washburne Refinery"],
    "SaltFlatsToOasisTown":                    ["Oasis", "Wurmwater"],
    "SaltFlatsToRefinery":                     ["Washburne Refinery", "Wurmwater"],
    "SaltFlatsToShipGraveyard":                ["The Rustyards", "Wurmwater"],
    "SaltFlatsToSpire":                        ["Magnys Lighthouse", "Wurmwater"],
    # "SaltFlatsToWormBelly":                  ["Wurmwater" "The Leviathan's Lair"],
    "ShipGraveyardToSaltFlats":                ["Wurmwater", "The Rustyards"],
    # "SpireToOasisTown":                      ["Oasis", "Magnys Lighthouse"],
    "SpireToSaltFlats":                        ["Wurmwater", "Magnys Lighthouse"],
    "WormBellyToOasisTown":                    ["The Leviathan's Lair", "Oasis"],
    "WormBellyToSaltFlats":                    ["The Leviathan's Lair", "Wurmwater"],
    # "CliffsToUnderground":                   ["Candlerakk's Cragg", "Hunter's Grotto"],
    # "PowerStationToUnderground":             ["Ardorton Station", "Hunter's Grotto"],
    "Sage_Travel_CliffsToShip":                ["Terminus", "Candlerakk's Cragg"],
    "Sage_Travel_CliffsToUnderground":         ["Candlerakk's Cragg", "Hunter's Grotto"],
    "Sage_Travel_PowerStationToRockForest":    ["Ardorton Station", "Scylla's Grove"],
    "Sage_Travel_PowerStationToUnderground":   ["Hunter's Grotto", "Ardorton Station"],
    "Sage_Travel_RockForestToPowerStation":    ["Scylla's Grove", "Ardorton Station"],
    "Sage_Travel_RockForestToUnderground":     ["Hunter's Grotto", "Scylla's Grove"],
    # "Sage_Travel_RockForestToVillage":       ["Scylla's Grove", "Hunter's Grotto"], # ??
    "Sage_Travel_ShipToCliffs":                ["Candlerakk's Cragg", "Terminus"],
    "Sage_Travel_UndergroundToCliffs":         ["Hunter's Grotto", "Candlerakk's Cragg"],
    "Sage_Travel_UndergroundToPowerStation":   ["Ardorton Station", "Hunter's Grotto"],
    "Sage_Travel_UndergroundToRockForest":     ["Scylla's Grove", "Hunter's Grotto"],

    # FastTravelStationDefinition
    "Hunger":                        ["Gluttony Gulch"],
    "Xmas":                          ["Marcus's Mercenary Shop"],
    "BackburnerIntro":               ["The Backburner"],
    "BackBurner":                    ["The Backburner"],
    "Helios":                        ["Helios Fallen"],
    "OldDust":                       ["Dahl Abandon"],
    "ResearchCenter":                ["Mt. Scarab Research Center"],
    "Helios_OneWay":                 ["Helios Fallen"],
    "ResearchCenter_OneWay":         ["Mt. Scarab Research Center"],
    "SanctuaryIntro":                ["FFS Intro Sanctuary"],
    "Sandworm_OneWay":               ["The Burrows"],
    "CastleExterior":                ["Hatred's Shadow"],
    "CastleKeep":                    ["Dragon Keep"],
    "DarkForest":                    ["The Forest"],
    "DeadForest":                    ["Immortal Woods"],
    "Docks":                         ["Unassuming Docks"],
    "Dungeons":                      ["Lair of Infinite Agony"],
    "Mines":                         ["Mines of Avarice"],
    "Village":                       ["Flamerock Refuge"],
    "FyrestoneOneWay":               ["Arid Nexus Badlands"],
    "Interlude":                     ["The Dust"],
    "Lynchwood":                     ["Lynchwood"],
    "Outwash":                       ["Highlands Outwash"],
    "Sanctuary":                     ["Sanctuary"],
    "Wilhelm":                       ["End of the Line"],
    "Caverns":                       ["Caustic Caverns"],
    "DamTop":                        ["Bloodshot Ramparts"],
    # "Glacial":                       [],
    # "GlacialIgloo":                  [],
    "GoshDam":                       ["Bloodshot Stronghold"],
    "IceCanyon":                     ["Frostburn Canyon"],
    "IceEast":                       ["Three Horns Divide"],
    "IceWest":                       ["Three Horns Valley"],
    "SouthernShelfTown":             ["Southern Shelf"],
    "SouthpawFactory":               ["Southpaw Steam & Power"],
    "TundraExpress":                 ["Tundra Express"],
    "TundraExpressSecret":           ["Tundra Express"],
    "TundraTrain":                   ["End of the Line"],
    "Cliffs":                        ["Thousand Cuts"],
    "Cliffs_Boss":                   ["The Bunker"],
    "Grass_A":                       ["Highlands"],
    "Grass_B":                       ["Highlands"],
    "Grass_C":                       ["Highlands"],
    "HyperionCity":                  ["Opportunity"],
    "PandoraPark":                   ["Wildlife Exploitation Preserve"],
    "TheFridge":                     ["The Fridge"],
    "Ash":                           ["Eridium Blight"],
    "CraterLake":                    ["Sawtooth Cauldron"],
    "FinalBossAscent":               ["Hero's Pass"],
    "OnFireStone":                   ["Arid Nexus Boneyard"],
    "Volcano_Boss_A":                ["Vault of the Warrior"],
    "Volcano_Boss_B":                ["Vault of the Warrior"],
    "PumpkinPatch":                  ["Hallowed Hollow"],
    "BadassBar":                     ["Badass Crater Bar"],
    "Beatdown":                      ["The Beatdown"],
    "Forge":                         ["The Forge"],
    "IrisCrater":                    ["Badass Crater"],
    "SouthernRaceway":               ["Southern Raceway"],
    "TestingZone":                   ["Digistruct Peak"],
    "EasterTravel":                  ["Wam Bam Island"],
    "Vday":                          ["Rotgut Distillery"],
    "Caves":                         ["Hayter's Folly"],
    "OasisTown":                     ["Oasis"],
    "Refinary":                      ["Washburne Refinery"],
    "SaltFlats":                     ["Wurmwater"],
    "ShipGraveyard":                 ["The Rustyards"],
    "Spire":                         ["Magnys Lighthouse"],
    "TopOfSpire":                    ["Magnys Lighthouse"],
    "HyperionShip":                  ["Terminus"],
    "PowerStation":                  ["Ardorton Station"],
    "RockForest":                    ["Scylla's Grove"],
    "SageCliffs":                    ["Candlerakk's Cragg"],
    "Underground":                   ["Hunter's Grotto"],
    "Underground_Lodge":             ["Hunter's Grotto"],
}

travel_targets = {
    #  "Windshear Waste":                    "GD_FastTravelStations.Zone1.GlacialIgloo",
     "Arid Nexus Boneyard":                "GD_FastTravelStations.Zone3.OnFireStone",
     "The Holy Spirits":                   "GD_LevelTravelStations.Zone2.LuckysToGrass",
     "Southpaw Steam & Power":             "GD_FastTravelStations.Zone1.SouthpawFactory",
     "Sanctuary Hole":                     "GD_LevelTravelStations.Zone1.SanctuaryHoleToIce",
     "Hero's Pass":                        "GD_FastTravelStations.Zone3.FinalBossAscent",
     "Bloodshot Stronghold":               "GD_FastTravelStations.Zone1.GoshDam",
     "Three Horns Valley":                 "GD_FastTravelStations.Zone1.IceWest",
     "Sanctuary":                          "GD_FastTravelStations.Sanctuary.Sanctuary",
     "Thousand Cuts":                      "GD_FastTravelStations.Zone2.Cliffs",
     "End of the Line":                    "GD_LevelTravelStations.WilhelmToTundraExpress",
     "Wildlife Exploitation Preserve":     "GD_FastTravelStations.Zone2.PandoraPark",
     "Terramorphous Peak":                 "GD_LevelTravelStations.Zone2.ThresherRaidToCliffs",
     "Tundra Express":                     "GD_FastTravelStations.Zone1.TundraExpress",
     "The Fridge":                         "GD_FastTravelStations.Zone2.TheFridge",
     "Fink's Slaughterhouse":              "GD_LevelTravelStations.Zone2.BanditSlaughterToFridge",
     "Southern Shelf Bay":                 "GD_LevelTravelStations.Zone1.CoveToWaterfront",
     "Frostburn Canyon":                   "GD_FastTravelStations.Zone1.IceCanyon",
     "Three Horns Divide":                 "GD_FastTravelStations.Zone1.IceEast",
     "Highlands":                          "GD_FastTravelStations.Zone2.Grass_A",
     "Natural Selection Annex":            "GD_LevelTravelStations.Zone2.CreatureSlaughterToPandoraPark",
     "The Dust":                           "GD_FastTravelStations.Interlude.Interlude",
     "Friendship Gulag":                   "GD_LevelTravelStations.Interlude.HypInterToInterlude",
     "Opportunity":                        "GD_FastTravelStations.Zone2.HyperionCity",
     "Bloodshot Ramparts":                 "GD_LevelTravelStations.Zone1.DamTopToDam",
     "Arid Nexus Badlands":                "GD_FastTravelStations.FyrestoneOneWay",
     "Southern Shelf":                     "GD_LevelTravelStations.Zone1.WaterfrontToGlacial",
     "Highlands Outwash":                  "GD_FastTravelStations.Outwash",
     "Caustic Caverns":                    "GD_FastTravelStations.Zone1.Caverns",
     "Lynchwood":                          "GD_FastTravelStations.Interlude.Lynchwood",
     "Sawtooth Cauldron":                  "GD_FastTravelStations.Zone3.CraterLake",
     "Ore Chasm":                          "GD_LevelTravelStations.Zone3.RobotSlaughterToAsh",
     "The Bunker":                         "GD_FastTravelStations.Zone2.Cliffs_Boss",
     "Control Core Angel":                 "GD_LevelTravelStations.Zone2.VOGsChamberToBossCliffs",
     "Vault of the Warrior":               "GD_LevelTravelStations.Zone3.VolcanoToFinalBossAscent",
     "Eridium Blight":                     "GD_FastTravelStations.Zone3.Ash",
     "Gluttony Gulch":                     "GD_Allium_FastTravel.Hunger",
     "Marcus's Mercenary Shop":            "GD_Allium_FastTravel.Xmas",
     "Helios Fallen":                      "GD_Anemone_FastTravel.FastTravelStations.Helios",
     "FFS Boss Fight":                     "GD_Anemone_LevelTravel.SanctuaryToResearchCenter",
     "The Backburner":                     "GD_Anemone_FastTravel.FastTravelStations.BackBurner",
     "FFS Intro Sanctuary":                "GD_Anemone_FastTravel.SanctuaryIntro",
     "Dahl Abandon":                       "GD_Anemone_FastTravel.FastTravelStations.OldDust",
     "Mt. Scarab Research Center":         "GD_Anemone_FastTravel.FastTravelStations.ResearchCenter",
     "The Burrows":                        "GD_Anemone_FastTravel.Sandworm_OneWay",
     "Writhing Deep":                      "GD_Anemone_LevelTravel.RaidBossToSandwormCavern",
     "The Forest":                         "GD_Aster_FastTravel.DarkForest",
     "Immortal Woods":                     "GD_Aster_FastTravel.DeadForest",
     "Dragon Keep":                        "GD_Aster_FastTravel.CastleExterior",
     "Unassuming Docks":                   "GD_Aster_FastTravel.Docks",
     "Flamerock Refuge":                   "GD_Aster_FastTravel.Village",
     "Hatred's Shadow":                    "GD_Aster_FastTravel.CastleKeep",
     "Lair of Infinite Agony":             "GD_Aster_FastTravel.Dungeons",
     "Murderlin's Temple":                 "GD_Aster_LevelTravel.TempleOfSlaughterToVillage",
     "Mines of Avarice":                   "GD_Aster_FastTravel.Mines",
     "The Winged Storm":                   "GD_Aster_LevelTravel.DungeonRaidToDungeon",
     "Hallowed Hollow":                    "GD_Flax_FastTravel.PumpkinPatch",
     "Torgue Arena":                       "GD_Iris_LevelTravelStations.Dogleg1.ArenaToCrater",
     "Torgue Arena TAS":                   "GD_Iris_LevelTravelStations.Dogleg1.ArenaTASToCrater", # special case
     "Torgue Arena Ring":                  "GD_Iris_LevelTravelStations.Dogleg1.BackdoorToCrater", # special case
     "The Beatdown":                       "GD_Iris_FastTravelStations.Beatdown",
     "The Forge":                          "GD_Iris_FastTravelStations.Forge",
     "Badass Crater":                      "GD_Iris_FastTravelStations.Hub.IrisCrater",
     "Southern Raceway":                   "GD_Iris_FastTravelStations.SouthernRaceway",
     "Pyro Pete's Bar":                    "GD_Iris_LevelTravelStations.PyroPetesToBeatdown",
     "Badass Crater Bar":                  "GD_Iris_FastTravelStations.BadassBar",
     "Digistruct Peak":                    "GD_Lobelia_FastTravel.TestingZone",
     "Wam Bam Island":                     "GD_Nasturtium_FastTravel.EasterTravel",
     "Rotgut Distillery":                  "GD_Nasturtium_FastTravel.Vday",
     "The Leviathan's Lair":               "GD_Orchid_LevelTravel.WormBelly.WormBellyToOasisTown",
     "Washburne Refinery":                 "GD_Orchid_FastTravel.Refinary",
     "Wurmwater":                          "GD_Orchid_FastTravel.SaltFlats.SaltFlats",
     "Magnys Lighthouse":                  "GD_Orchid_FastTravel.Spire",
     "The Rustyards":                      "GD_Orchid_FastTravel.ShipGraveyard",
     "Hayter's Folly":                     "GD_Orchid_FastTravel.Caves",
     "Oasis":                              "GD_Orchid_FastTravel.OasisTown.OasisTown",
     "Ardorton Station":                   "GD_Sage_FastTravel.PowerStation",
     "Hunter's Grotto":                    "GD_Sage_FastTravel.Underground",
     "Candlerakk's Cragg":                 "GD_Sage_FastTravel.SageCliffs",
     "Terminus":                           "GD_Sage_LevelTravel.Sage_Travel_ShipToCliffs",
     "Scylla's Grove":                     "GD_Sage_FastTravel.RockForest",
}
