# TODO: split into vault symbols and enemies files
vault_symbol_pathname_to_name = {
    "SanctuaryAir_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":               "Symbol Sanctuary: Rooftop",
    "SanctuaryAir_P.TheWorld:PersistentLevel.WillowInteractiveObject_1":               "Symbol Sanctuary: Moxxi's Corner",
    "SanctuaryAir_P.TheWorld:PersistentLevel.WillowInteractiveObject_2":               "Symbol Sanctuary: Trash Corner",
    "SanctuaryAir_P.TheWorld:PersistentLevel.WillowInteractiveObject_263":             "Symbol Sanctuary: Tire Corner",
    "SanctuaryAir_P.TheWorld:PersistentLevel.WillowInteractiveObject_98":              "Symbol Sanctuary: Parkour Door",

    "Sanctuary_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":                  "Symbol Sanctuary: Rooftop",
    "Sanctuary_P.TheWorld:PersistentLevel.WillowInteractiveObject_1":                  "Symbol Sanctuary: Moxxi's Corner",
    "Sanctuary_P.TheWorld:PersistentLevel.WillowInteractiveObject_2":                  "Symbol Sanctuary: Trash Corner",
    "Sanctuary_P.TheWorld:PersistentLevel.WillowInteractiveObject_263":                "Symbol Sanctuary: Tire Corner",
    "Sanctuary_P.TheWorld:PersistentLevel.WillowInteractiveObject_98":                 "Symbol Sanctuary: Parkour Door",
    "Ash_P.TheWorld:PersistentLevel.WillowInteractiveObject_1":                        "Symbol EridiumBlight: Hellsfont Crate",
    "Ash_P.TheWorld:PersistentLevel.WillowInteractiveObject_3":                        "Symbol EridiumBlight: Stairs Door",
    "Ash_P.TheWorld:PersistentLevel.WillowInteractiveObject_518":                      "Symbol EridiumBlight: Refund Building",
    "BanditSlaughter_P.TheWorld:PersistentLevel.WillowInteractiveObject_29":           "Symbol Fink's: Column",
    "Boss_Cliffs_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":                "Symbol Bunker: Backside",
    "Boss_Volcano_P.TheWorld:PersistentLevel.WillowInteractiveObject_181":             "Symbol VaultOfTheWarrior: Elevator Bottom",
    "Cove_P.TheWorld:PersistentLevel.WillowInteractiveObject_180":                     "Symbol SouthernShelfBay: Blackburn Cove Corner",
    "Cove_P.TheWorld:PersistentLevel.WillowInteractiveObject_235":                     "Symbol SouthernShelfBay: Ice Flows Shipwreck",
    "CraterLake_P.TheWorld:PersistentLevel.WillowInteractiveObject_27":                "Symbol Sawtooth: Refinery Container",
    "CraterLake_P.TheWorld:PersistentLevel.WillowInteractiveObject_7":                 "Symbol Sawtooth: Elevator",
    "CreatureSlaughter_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":          "Symbol NaturalSelectionAnnex: Crate Ceiling",
    "FinalBossAscent_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":            "Symbol HerosPass: Strut",
    "FinalBossAscent_P.TheWorld:PersistentLevel.WillowInteractiveObject_6":            "Symbol HerosPass: Spawn",
    "Fridge_P.TheWorld:PersistentLevel.WillowInteractiveObject_89":                    "Symbol Fridge: Secret Stash",
    "Fridge_P.TheWorld:PersistentLevel.WillowInteractiveObject_90":                    "Symbol Fridge: Sheetmetal Roof",
    "Frost_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_5":                "Symbol ThreeHornsValley: Slums Wall",           #A Dam Fine Rescue mission
    "Frost_P.TheWorld:PersistentLevel.WillowInteractiveObject_31":                     "Symbol ThreeHornsValley: Frostsprings Wall",
    "Frost_P.TheWorld:PersistentLevel.WillowInteractiveObject_5":                      "Symbol ThreeHornsValley: Frostsprings Shack",
    "Fyrestone_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":                  "Symbol AridNexusBoneyard: Pipe",
    "Fyrestone_P.TheWorld:PersistentLevel.WillowInteractiveObject_3":                  "Symbol AridNexusBoneyard: Safety",
    "Glacial_P.TheWorld:PersistentLevel.WillowInteractiveObject_214":                  "Symbol WindshearWaste: Claptrap's Closet",
    "Grass_Cliffs_P.TheWorld:PersistentLevel.WillowInteractiveObject_174":             "Symbol ThousandCuts: Buzzard Factory",
    "Grass_Cliffs_P.TheWorld:PersistentLevel.WillowInteractiveObject_302":             "Symbol ThousandCuts: No Man's Land Shack",
    "Grass_Lynchwood_P.TheWorld:PersistentLevel.WillowInteractiveObject_298":          "Symbol Lynchwood: Gunslinger Roof",
    "Grass_Lynchwood_P.TheWorld:PersistentLevel.WillowInteractiveObject_601":          "Symbol Lynchwood: Main Street",
    "Grass_P.TheWorld:PersistentLevel.WillowInteractiveObject_346":                    "Symbol Highlands: Highlands Tower",
    "HypInterlude_P.TheWorld:PersistentLevel.WillowInteractiveObject_12":              "Symbol FriendshipGulag: Gulag Container",
    "HyperionCity_P.TheWorld:PersistentLevel.WillowInteractiveObject_180":             "Symbol Opportunity: Construction Site",
    "HyperionCity_P.TheWorld:PersistentLevel.WillowInteractiveObject_181":             "Symbol Opportunity: Office Bridge",
    "Ice_P.TheWorld:PersistentLevel.WillowInteractiveObject_238":                      "Symbol ThreeHornsDivide: Drydocks Corner",
    "Ice_P.TheWorld:PersistentLevel.WillowInteractiveObject_5":                        "Symbol ThreeHornsDivide: Billboard",
    "Ice_P.TheWorld:PersistentLevel.WillowInteractiveObject_79":                       "Symbol ThreeHornsDivide: Windbreak Wall",
    "Interlude_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_26":           "Symbol Dust: Speedway Wall",
    "Interlude_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_4":            "Symbol Dust: Buzzard Pad",
    "Interlude_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_5":            "Symbol Dust: Moonshiner Lid",
    "caverns_p.TheWorld:PersistentLevel.WillowInteractiveObject_641":                  "Symbol CausticCaverns: Gravestone Feature",
    "caverns_p.TheWorld:PersistentLevel.WillowInteractiveObject_89":                   "Symbol CausticCaverns: Bloody Ladder",
    "dam_p.TheWorld:PersistentLevel.WillowInteractiveObject_137":                      "Symbol BloodshotStronghold: Pizza Intercom",
    "dam_p.TheWorld:PersistentLevel.WillowInteractiveObject_138":                      "Symbol BloodshotStronghold: Switch Room",
    "damtop_p.TheWorld:PersistentLevel.WillowInteractiveObject_0":                     "Symbol BloodshotRamparts: Ramp",
    "icecanyon_p.TheWorld:PersistentLevel.WillowInteractiveObject_51":                 "Symbol Frostburn: Blisterpus Cave",
    "icecanyon_p.TheWorld:PersistentLevel.WillowInteractiveObject_53":                 "Symbol Frostburn: Ashmouth Pit",
    "Iris_DL1_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_678":           "Symbol TorgueArenaRing: Arena Wall",
    "Iris_DL1_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_772":           "Symbol TorgueArenaRing: Arena Ladder",
    "Iris_DL2_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_425":           "Symbol Beatdown: Underpass",
    "Iris_DL2_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_79":            "Symbol Beatdown: School Bus",
    "Iris_DL3_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_214":           "Symbol Forge: Smack Talker",
    "Iris_DL3_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_425":           "Symbol Forge: Lava",
    "Iris_DL3_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_61":            "Symbol Forge: Housing",
    "Iris_Hub2_P.TheWorld:PersistentLevel.WillowInteractiveObject_6":                  "Symbol SouthernRaceway: Zer0 Poster",
    "Iris_Hub2_P.TheWorld:PersistentLevel.WillowInteractiveObject_9":                  "Symbol SouthernRaceway: Maya Poster",
    "Iris_Hub_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_11":            "Symbol BadassCrater: Badass Highway",
    "Iris_Hub_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_12":            "Symbol BadassCrater: Beatdown Door",
    "Iris_Hub_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_678":           "Symbol BadassCrater: Billboard Lower",
    "Iris_Hub_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_78":            "Symbol BadassCrater: Billboard Upper",
    "Luckys_P.TheWorld:PersistentLevel.WillowInteractiveObject_16":                    "Symbol HolySpirits: Bathroom",
    "ORCHID_CAVES_DYNAMIC.TheWorld:PersistentLevel.WillowInteractiveObject_347":       "Symbol HaytersFolly: Hot Springs Crate",
    "ORCHID_CAVES_DYNAMIC.TheWorld:PersistentLevel.WillowInteractiveObject_461":       "Symbol HaytersFolly: Grendel Exit",
    "Orchid_OasisTown_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_347":   "Symbol Oasis: Kronus",
    "Orchid_OasisTown_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_348":   "Symbol Oasis: Lair Exit",       #X Marks the Spot Mission
    "Orchid_OasisTown_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_349":   "Symbol Oasis: Lionel Docks",
    "Orchid_OasisTown_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_367":   "Symbol Oasis: Coral Island",
    "Orchid_Refinery_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_496":    "Symbol WashburneRefinery: P3RV-E Lair",
    "Orchid_Refinery_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_497":    "Symbol WashburneRefinery: Forge Array",
    "Orchid_SaltFlats_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_347":   "Symbol Wurmwater: Rustyard Corridor",
    "Orchid_SaltFlats_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_400":   "Symbol Wurmwater: Scarlett's Ship",
    "Orchid_SaltFlats_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_401":   "Symbol Wurmwater: The Dish",
    "Orchid_ShipGraveyard_P.TheWorld:PersistentLevel.WillowInteractiveObject_22":      "Symbol Rustyards: Maroonie's Clipper",
    "Orchid_ShipGraveyard_P.TheWorld:PersistentLevel.WillowInteractiveObject_23":      "Symbol Rustyards: Rustyards Fence",
    "Orchid_Spire_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_10":        "Symbol MagnysLighthouse: House",
    "Orchid_Spire_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_22":        "Symbol MagnysLighthouse: Lighthouse",
    "Orchid_WormBelly_P.TheWorld:PersistentLevel.WillowInteractiveObject_497":         "Symbol LeviathansLair: Lair",
    "PandoraPark_P.TheWorld:PersistentLevel.WillowInteractiveObject_273":              "Symbol WildlifePreserve: Dockyard Roof",
    "PandoraPark_P.TheWorld:PersistentLevel.WillowInteractiveObject_274":              "Symbol WildlifePreserve: Broken Boulevard",
    "RobotSlaughter_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_15":      "Symbol OreChasm: Elevator",
    "Sage_Cliffs_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_129":        "Symbol CandlerakksCrag: Elite Crossing House",
    "Sage_Cliffs_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_71":         "Symbol CandlerakksCrag: Near Voracidous",
    "Sage_Cliffs_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_84":         "Symbol CandlerakksCrag: Rouge's Lair",
    "Sage_HyperionShip_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":          "Symbol Terminus: Terminus",     #crouch
    "Sage_PowerStation_P.TheWorld:PersistentLevel.WillowInteractiveObject_29":         "Symbol ArdortonStation: Woundspike's Lair",
    "Sage_PowerStation_P.TheWorld:PersistentLevel.WillowInteractiveObject_5":          "Symbol ArdortonStation: Psycho Surgery",
    "Sage_PowerStation_P.TheWorld:PersistentLevel.WillowInteractiveObject_6":          "Symbol ArdortonStation: Ardo Farm",
    "Sage_PowerStation_P.TheWorld:PersistentLevel.WillowInteractiveObject_7":          "Symbol ArdortonStation: Dribble's Lair",
    "Sage_RockForest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_10":     "Symbol ScyllasGrove: Low Gut Rut Wall",
    "Sage_RockForest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_6":      "Symbol ScyllasGrove: Urine Wall",
    "Sage_RockForest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_8":      "Symbol ScyllasGrove: Upper Village",
    "Sage_RockForest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_9":      "Symbol ScyllasGrove: Lower Village",
    "Sanctuary_Hole_P.TheWorld:PersistentLevel.WillowInteractiveObject_6":             "Symbol SanctuaryHole: Staircase Wall",
    "SouthernShelf_P.TheWorld:PersistentLevel.WillowInteractiveObject_181":            "Symbol SouthernShelf: Flynt's Ship",
    "SouthernShelf_P.TheWorld:PersistentLevel.WillowInteractiveObject_397":            "Symbol SouthernShelf: Safehouse",
    "SouthpawFactory_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_398":    "Symbol Southpaw: Parkour",
    "SouthpawFactory_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_399":    "Symbol Southpaw: Engine",
    "SouthpawFactory_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_46":     "Symbol Southpaw: Ladder",
    "ThresherRaid_P.TheWorld:PersistentLevel.WillowInteractiveObject_116":             "Symbol TerramorphousPeak: Dropdown",
    "ThresherRaid_P.TheWorld:PersistentLevel.WillowInteractiveObject_364":             "Symbol TerramorphousPeak: Elevator",
    "TundraTrain_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":                "Symbol EndOfTheLine: Wilhelm Wall",
    "tundraexpress_p.TheWorld:PersistentLevel.WillowInteractiveObject_206":            "Symbol TundraExpress: Fork Shack",
    "tundraexpress_p.TheWorld:PersistentLevel.WillowInteractiveObject_207":            "Symbol TundraExpress: Facility Roof",
    "BackBurnerInteractive.TheWorld:PersistentLevel.WillowInteractiveObject_2":        "Symbol Backburner: Zed's",
    "BackBurnerInteractive.TheWorld:PersistentLevel.WillowInteractiveObject_3":        "Symbol Backburner: Entrance",
    "CastleExterior_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":             "Symbol HatredsShadow: Sir Boil",
    "CastleExterior_P.TheWorld:PersistentLevel.WillowInteractiveObject_1":             "Symbol HatredsShadow: Nefarious Elevator",
    "CastleExterior_P.TheWorld:PersistentLevel.WillowInteractiveObject_4":             "Symbol HatredsShadow: Sir Mash",
    "CastleKeep_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_0":           "Symbol DragonKeep: Sacrifice Staircase",
    "Dark_Forest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_0":          "Symbol Forest: Blood Tree Camp",
    "Dark_Forest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_1":          "Symbol Forest: Glenn's Cottage",
    "Dead_Forest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_1":          "Symbol ImmortalWoods: Fields of the Fallen",
    "Dead_Forest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_19":         "Symbol ImmortalWoods: Sacred Ruins Upper",
    "Dead_Forest_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_20":         "Symbol ImmortalWoods: Sacred Ruins Lower",
    "Docks_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":                      "Symbol UnassumingDocks: Temple Shoreline",
    "Docks_P.TheWorld:PersistentLevel.WillowInteractiveObject_1":                      "Symbol UnassumingDocks: Forlorn Ruins",
    "Docks_P.TheWorld:PersistentLevel.WillowInteractiveObject_2":                      "Symbol UnassumingDocks: Hamlet Building",
    "DungeonRaid_P.TheWorld:PersistentLevel.WillowInteractiveObject_0":                "Symbol WingedStorm: The Winged Storm",
    "Dungeon_P.TheWorld:PersistentLevel.WillowInteractiveObject_307":                  "Symbol LairOfInfiniteAgony: Platform Corridor",
    "Dungeon_P.TheWorld:PersistentLevel.WillowInteractiveObject_308":                  "Symbol LairOfInfiniteAgony: Hall of the Dead",
    "Dungeon_P.TheWorld:PersistentLevel.WillowInteractiveObject_90":                   "Symbol LairOfInfiniteAgony: Wailer Drop",
    "Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_388":         "Symbol HeliosFallen: Moonshot Complaint Dept",
    "Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_446":         "Symbol HeliosFallen: The Freightway",
    "Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_447":         "Symbol HeliosFallen: Hellion Hole",
    "Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_859":         "Symbol HeliosFallen: Munitions Loading",
    "Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_892":         "Symbol HeliosFallen: Fire Control Alpha",
    "Helios_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_894":         "Symbol HeliosFallen: The Hold",
    "Mines_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_1":                "Symbol MinesOfAvarice: Ingot Processing",
    "Mines_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_16":               "Symbol MinesOfAvarice: Cube Room",
    "Mines_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_47":               "Symbol MinesOfAvarice: Greedtooth's Lair",
    "OldDust_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_187":        "Symbol DahlAbandon: Simon's Perch Climb",
    "OldDust_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_269":        "Symbol DahlAbandon: Ride's End",
    "OldDust_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_36":         "Symbol DahlAbandon: Redclaw Rise Cliff",
    "OldDust_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_59":         "Symbol DahlAbandon: The Veiny Shaft",
    "OldDust_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_84":         "Symbol DahlAbandon: Simon's Perch Container",
    "ResearchCenter_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_164": "Symbol MtScarab: Test Candidate Detention",
    "ResearchCenter_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_167": "Symbol MtScarab: 02 Staircase",
    "ResearchCenter_Research.TheWorld:PersistentLevel.WillowInteractiveObject_737":    "Symbol MtScarab: Experimentation Room",
    "Sage_Underground_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_68":    "Symbol HuntersGrotto: Arizona's Lair",
    "Sage_Underground_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_69":    "Symbol HuntersGrotto: Grotto Lodge",
    "Sage_Underground_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_70":    "Symbol HuntersGrotto: Grotto Start",
    "Sage_Underground_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_71":    "Symbol HuntersGrotto: Dahl Door",
    "SandwormLair_GD.TheWorld:PersistentLevel.WillowInteractiveObject_1161":           "Symbol WrithingDeep: Elevator Room",
    "SandwormLair_GD.TheWorld:PersistentLevel.WillowInteractiveObject_1162":           "Symbol WrithingDeep: Southern Top",
    "SandwormLair_GD.TheWorld:PersistentLevel.WillowInteractiveObject_1163":           "Symbol WrithingDeep: Northern Top",
    "Sandworm_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_46":        "Symbol Burrows: Hyperion's Grave",
    "Sandworm_Interactive.TheWorld:PersistentLevel.WillowInteractiveObject_60":        "Symbol Burrows: Burrows Cliff",
    "TempleSlaughter_Combat.TheWorld:PersistentLevel.WillowInteractiveObject_1":       "Symbol MurderlinsTemple: The Nursery",
    "TempleSlaughter_Combat.TheWorld:PersistentLevel.WillowInteractiveObject_3":       "Symbol MurderlinsTemple: Below Murderlin",
    "Village_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_206":            "Symbol FlamerockRefuge: Outskirts",
    "Village_Dynamic.TheWorld:PersistentLevel.WillowInteractiveObject_383":            "Symbol FlamerockRefuge: Parkour",
}

vending_machine_position_to_name = {
    "11617,1242":           "Vending Sanctuary Crimson Base: Guns",
    "11624,1267":           "Vending Sanctuary Crimson Base: Guns",
    "11584,1403":           "Vending Sanctuary Crimson Base: Ammo",
    "11599,1407":           "Vending Sanctuary Crimson Base: Ammo",
    "8434,-3526":           "Vending Sanctuary Zed's: Ammo",
    "8387,-4248":           "Vending Sanctuary Zed's: Meds 1",
    "9265,-4415":           "Vending Sanctuary Zed's: Meds 2",
    "11207,8562":           "Vending Sanctuary Marcus's: Ammo",
    "11430,8505":           "Vending Sanctuary Marcus's: Marcus",
    "10569,6224":           "Vending Sanctuary Marcus's: Meds",
    "11207,8546":           "Vending Sanctuary Marcus's: Ammo",
    "11382,8937":           "Vending Sanctuary Marcus's: Marcus",
    "30186,33162":          "Vending FriendshipGulag: Meds",
    "30186,33347":          "Vending FriendshipGulag: Ammo",
    "-26727,32659":         "Vending Dust Ellie's: Meds",
    "-26727,32512":         "Vending Dust Ellie's: Ammo",
    "27889,-17657":         "Vending SouthernShelf Hammerlock's: Guns",
    "29743,-13024":         "Vending SouthernShelf Liar's: Ammo",
    "27325,-12299":         "Vending SouthernShelf Liar's: Meds",
    "25657,-28009":         "Vending SouthernShelf Safehouse: Meds",
    "80436,-43687":         "Vending SouthernShelf Dragon: Meds",
    "70136,-42976":         "Vending SouthernShelf Dragon: Ammo",
    "19286,-29147":         "Vending SouthernShelfBay Spawn: Ammo",
    "19291,-29039":         "Vending SouthernShelfBay Spawn: Meds",
    "1460,-8267":           "Vending SouthernShelfBay Cove: Guns",
    "1314,-7353":           "Vending SouthernShelfBay Cove: Ammo",
    "1166,-7430":           "Vending SouthernShelfBay Cove: Meds",
    "-40344,38442":         "Vending ThreeHornsDivide Jump: Ammo",
    "-40361,38650":         "Vending ThreeHornsDivide Jump: Meds",
    "22261,38591":          "Vending ThreeHornsDivide Crossroads: Guns",
    "22101,38575":          "Vending ThreeHornsDivide Crossroads: Ammo",
    "21781,38848":          "Vending ThreeHornsDivide Crossroads: Meds",
    "17576,-8728":          "Vending ThreeHornsValley Motel: Guns",
    "17493,-8598":          "Vending ThreeHornsValley Motel: Ammo",
    "17040,-10311":         "Vending ThreeHornsValley Motel: Meds",
    "-4700,19685":          "Vending Southpaw: Ammo",
    "-4706,19520":          "Vending Southpaw: Meds",
    "3829,-2432":           "Vending Frostburn Spawn: Ammo",
    "3656,-2410":           "Vending Frostburn Spawn: Meds",
    "16417,-20419":         "Vending Frostburn Firehawk: Ammo",
    "16466,-20227":         "Vending Frostburn Firehawk: Meds",
    "-27706,5562":          "Vending BloodshotStronghold: Ammo",
    "-27547,5571":          "Vending BloodshotStronghold: Meds",
    "-58424,20912":         "Vending BloodshotRamparts: Ammo",
    "-58602,20955":         "Vending BloodshotRamparts: Meds",
    "-41219,13428":         "Vending TundraExpress Spawn: Ammo",
    "-41076,13467":         "Vending TundraExpress Spawn: Meds",
    "1854,79":              "Vending TundraExpress Farm: Guns",
    "-13285,18100":         "Vending TundraExpress Tina: Ammo",
    "-20192,34880":         "Vending EndOfTheLine: Ammo",
    "-20210,35067":         "Vending EndOfTheLine: Meds",
    "1597,20937":           "Vending Fridge Spawn: Ammo",
    "1688,21050":           "Vending Fridge Spawn: Meds",
    "8315,-6885":           "Vending Fridge Elevator: Ammo",
    "8316,-7089":           "Vending Fridge Elevator: Meds",
    "22535,9903":           "Vending Fink's: Guns",
    "22342,9748":           "Vending Fink's: Ammo",
    "22171,9605":           "Vending Fink's: Meds",
    "53791,73317":          "Vending HighlandsOutwash: Ammo",
    "53627,73348":          "Vending HighlandsOutwash: Meds",
    "16764,-6564":          "Vending Highlands Bridge: Ammo",
    "16733,-6406":          "Vending Highlands Bridge: Meds",
    "66989,4112":           "Vending Highlands Overlook: Guns",
    "66849,4450":           "Vending Highlands Overlook: Ammo",
    # "66917,1491":           "Vending Highlands Overlook: Meds",
    # "57752,45408":          "Vending Extraction Plant: Meds",
    # "-3426,-15360":         "Vending Hyperion Bridge: Meds",
    "472,2348":             "Vending HolySpirits: Guns",
    "1182,970":             "Vending HolySpirits: Ammo",
    "1118,432":             "Vending HolySpirits: Meds",
    "-23928,-5742":         "Vending Dust Speedway: Ammo",
    "-24094,-5698":         "Vending Dust Speedway: Meds",
    "36756,-6778":          "Vending Dust Steve: Ammo",
    "36826,-6644":          "Vending Dust Steve: Meds",
    "39735,15512":          "Vending Dust Dahlwell: Meds",
    "39544,15451":          "Vending Dust Dahlwell: Ammo",
    "2730,-6726":           "Vending SanctuaryHole: Ammo",
    "2621,-6804":           "Vending SanctuaryHole: Meds",
    "-14800,2393":          "Vending CausticCaverns Spawn: Ammo",
    "-14795,2550":          "Vending CausticCaverns Spawn: Meds",
    "8817,8694":            "Vending CausticCaverns Shortcut: Guns",
    "-31556,66487":         "Vending WildlifePreserve Spawn: Ammo",
    "-31671,66271":         "Vending WildlifePreserve Spawn: Meds",
    "-25675,9895":          "Vending WildlifePreserve Halfway: Ammo",
    "-25797,10014":         "Vending WildlifePreserve Halfway: Meds",
    "-10416,-1355":         "Vending NaturalSelectionAnnex: Ammo",
    "-10426,-1500":         "Vending NaturalSelectionAnnex: Meds",
    "-17302,-9530":         "Vending ThousandCuts: Ammo",
    "-17474,-9552":         "Vending ThousandCuts: Meds",
    "11266,-22845":         "Vending Lynchwood Spawn: Ammo",
    "11433,-22844":         "Vending Lynchwood Spawn: Meds",
    "30956,-25556":         "Vending Lynchwood Gunslinger: Guns",
    "24548,-5676":          "Vending Opportunity Spawn: Guns",
    "24532,-3513":          "Vending Opportunity Spawn: Ammo",
    "24065,-3513":          "Vending Opportunity Spawn: Meds",
    "13057,-8347":          "Vending Opportunity Office: Ammo",
    "12579,-8351":          "Vending Opportunity Office: Meds",
    "14975,-3411":          "Vending Opportunity Square: Ammo",
    "15301,-3746":          "Vending Opportunity Square: Meds",
    "79,2455":              "Vending Opportunity Residential: Guns",
    "65,1975":              "Vending Opportunity Residential: Ammo",
    "13548,15976":          "Vending Bunker: Ammo",
    "13495,15851":          "Vending Bunker: Meds",
    "-893,-47713":          "Vending EridiumBlight Spawn: Ammo",
    "-719,-47729":          "Vending EridiumBlight Spawn: Meds",
    "-9755,-6528":          "Vending EridiumBlight Extraction: Ammo",
    "-9739,-6359":          "Vending EridiumBlight Extraction: Meds",
    "27558,-40893":         "Vending EridiumBlight Refinery: Guns",
    "27422,-41023":         "Vending EridiumBlight Refinery: Ammo",
    "27760,-40695":         "Vending EridiumBlight Refinery: Meds",
    "-52976,-61745":        "Vending OreChasm: Guns",
    "-52649,-61758":        "Vending OreChasm: Ammo",
    "-52811,-61737":        "Vending OreChasm: Meds",
    "26036,40591":          "Vending Sawtooth Spawn: Ammo",
    "26162,40656":          "Vending Sawtooth Spawn: Meds",
    "22406,25541":          "Vending Sawtooth Elevator: Ammo",
    "-61941,12209":         "Vending AridNexusBoneyard Spawn: Ammo",
    "-62395,12297":         "Vending AridNexusBoneyard Spawn: Meds",
    "-13311,31034":         "Vending AridNexusBadlands Fyrestone: Ammo",
    "-12519,33977":         "Vending AridNexusBadlands Fyrestone: Meds",
    "-27127,27497":         "Vending AridNexusBadlands Baha: Guns",
    "21912,-13934":         "Vending HerosPass Spawn: Ammo",
    "22046,-14042":         "Vending HerosPass Spawn: Meds",
    "-13842,-3463":         "Vending VaultOfTheWarrior: Ammo",
    "-13973,-3522":         "Vending VaultOfTheWarrior: Meds",
    "-26342,-382":          "Vending TerramorphousPeak: Guns",
    "-26640,-559":          "Vending TerramorphousPeak: Ammo",
    "-26599,-746":          "Vending TerramorphousPeak: Meds",
    "-27293,-3670":         "Vending Oasis Town: Guns",
    "-18475,-2363":         "Vending Oasis Town: Ammo",
    "-18622,-2346":         "Vending Oasis Town: Meds",
    "46025,-60993":         "Vending Wurmwater Oasis Door: Ammo",
    "46142,-61099":         "Vending Wurmwater Oasis Door: Meds",
    "54921,5163":           "Vending Wurmwater Canyon: Guns",
    "54822,5046":           "Vending Wurmwater Canyon: Ammo",
    "-46810,32312":         "Vending Wurmwater Fen: Ammo",
    "-2262,272":            "Vending Wurmwater Ship: Guns",
    "-2267,75":             "Vending Wurmwater Ship: Ammo",
    "-2273,1189":           "Vending Wurmwater Ship: Meds",
    "10983,48962":          "Vending Wurmwater Rustyard: Guns",
    "-13165,22042":         "Vending HaytersFolly Spawn: Guns",
    "-12622,21830":         "Vending HaytersFolly Spawn: Ammo",
    "-13780,20634":         "Vending HaytersFolly Spawn: Meds",
    "-5408,-3514":          "Vending HaytersFolly Gee: Ammo",
    "-4899,-2502":          "Vending HaytersFolly Gee: Meds",
    "-25931,25124":         "Vending Rustyards Spawn: Ammo",
    "-26089,25248":         "Vending Rustyards Spawn: Meds",
    "27029,-20095":         "Vending Washburne Spawn: Ammo",
    "27002,-19922":         "Vending Washburne Spawn: Meds",
    "41794,495":            "Vending Washburne Hyperius: Ammo",
    "41622,474":            "Vending Washburne Hyperius: Meds",
    "-22807,-10281":        "Vending Magnys Spawn: Ammo",
    "-22937,-10486":        "Vending Magnys Spawn: Meds",
    "-2900,25942":          "Vending Leviathan Body: Ammo",
    "-2483,25214":          "Vending Leviathan Body: Meds",
    "-9856,-77793":         "Vending Leviathan Lair: Ammo",
    "-9951,-77667":         "Vending Leviathan Lair: Meds",
    "-9145,33092":          "Vending BadassCrater Spawn: Ammo",
    "-9200,32936":          "Vending BadassCrater Spawn: Meds",
    "25873,12851":          "Vending BadassCrater Town: Ammo",
    "25964,12667":          "Vending BadassCrater Town: Meds",
    "2144,-13193":          "Vending BadassCrater Forge: Torgue Vendor",
    "1436,-13206":          "Vending BadassCrater Forge: Ammo",
    "1675,-13230":          "Vending BadassCrater Forge: Meds",
    "1167,-11409":          "Vending TorgueArena Inner: Torgue Vendor",
    "-471,-11441":          "Vending TorgueArena Inner: Ammo",
    "-508,-11645":          "Vending TorgueArena Inner: Meds",
    "14192,-25105":         "Vending Beatdown Spawn: Torgue Vendor",
    "13843,-25266":         "Vending Beatdown Spawn: Ammo",
    "13683,-25434":         "Vending Beatdown Spawn: Meds",
    "-8393,-33132":         "Vending Beatdown Underpass: Torgue Vendor",
    "-8390,-33315":         "Vending Beatdown Underpass: Ammo",
    "-8399,-33499":         "Vending Beatdown Underpass: Meds",
    "-979,-14889":          "Vending Pete's: Torgue Vendor",
    "-542,-16377":          "Vending Pete's: Ammo",
    "-537,-16166":          "Vending Pete's: Meds",
    "32660,3715":           "Vending BadassBar: Torgue Vendor",
    "32666,3895":           "Vending BadassBar: Ammo",
    "32670,4066":           "Vending BadassBar: Meds",
    "-44247,42252":         "Vending Raceway: Torgue Vendor",
    "-44108,42363":         "Vending Raceway: Ammo",
    "-43982,42463":         "Vending Raceway: Meds",
    "37097,5507":           "Vending Forge Spawn: Torgue Vendor",
    "37221,5735":           "Vending Forge Spawn: Ammo",
    "37300,5922":           "Vending Forge Spawn: Meds",
    "40913,27674":          "Vending Forge Flyboy: Ammo",
    "40989,27801":          "Vending Forge Flyboy: Meds",
    "1055,-5886":           "Vending HuntersGrotto Lodge: Guns",
    "1208,-5891":           "Vending HuntersGrotto Lodge: Ammo",
    "900,-5890":            "Vending HuntersGrotto Lodge: Meds",
    "1981,-5757":           "Vending HuntersGrotto Lodge: Seraph Vendor",
    "8763,-5548":           "Vending ScyllasGrove Entrance: Guns",
    "7780,-4930":           "Vending ScyllasGrove Entrance: Ammo",
    "7819,-5218":           "Vending ScyllasGrove Entrance: Meds",
    "-29476,19838":         "Vending ScyllasGrove Pukey: Meds",
    "-22360,-43387":        "Vending Ardorton Entrance: Ammo",
    "-22498,-43332":        "Vending Ardorton Entrance: Meds",
    "-34414,4587":          "Vending Ardorton Exit: Ammo",
    "-34078,4605":          "Vending Ardorton Exit: Meds",
    "101267,-61847":        "Vending CandlerakksCrag Spawn: Ammo",
    "101275,-61691":        "Vending CandlerakksCrag Spawn: Meds",
    "60600,2505":           "Vending CandlerakksCrag Voracidous: Ammo",
    "60733,2425":           "Vending CandlerakksCrag Voracidous: Meds",
    "9896,28808":           "Vending Terminus Entrance: Ammo",
    "9790,28861":           "Vending Terminus Entrance: Meds",
    # "-2715,4303":           "Vending FlamerockRefuge: Seraph Vendor",
    "-5144,-8269":          "Vending FlamerockRefuge: Guns",
    "-4452,-8297":          "Vending FlamerockRefuge: Ammo",
    "-4723,-8339":          "Vending FlamerockRefuge: Meds",
    "-3704,-61590":         "Vending Forest Spawn: Ammo",
    "-3839,-61428":         "Vending Forest Spawn: Meds",
    "-20493,-34858":        "Vending ImmortalWoods Spawn: Ammo",
    "-20329,-34691":        "Vending ImmortalWoods Spawn: Meds",
    "823,-16453":           "Vending ImmortalWoods Vitality Grove: Ammo",
    "1035,-16468":          "Vending ImmortalWoods Vitality Grove: Meds",
    "4760,-1236":           "Vending MinesOfAvarice Spawn: Ammo",
    "4650,-1373":           "Vending MinesOfAvarice Spawn: Meds",
    "-13743,19706":         "Vending MinesOfAvarice Greedtooth: Ammo",
    "-13742,19530":         "Vending MinesOfAvarice Greedtooth: Meds",
    "19400,25669":          "Vending HatredsShadow Spawn: Ammo",
    "19618,25615":          "Vending HatredsShadow Spawn: Meds",
    "3963,-1982":           "Vending HatredsShadow Bridge: Guns",
    "3847,-1984":           "Vending HatredsShadow Bridge: Ammo",
    "3906,-2088":           "Vending HatredsShadow Bridge: Meds",
    "-2902,3361":           "Vending LairOfInfiniteAgony Spawn: Ammo",
    "-2382,2132":           "Vending LairOfInfiniteAgony Spawn: Meds",
    "156,-14330":           "Vending LairOfInfiniteAgony Daughter: Ammo",
    "-111,-14330":          "Vending LairOfInfiniteAgony Daughter: Meds",
    "8864,-6240":           "Vending LairOfInfiniteAgony Hall of the Dead: Mr. Miz",
    "127351,-18203":        "Vending DragonKeep: Ammo",
    "127553,-18221":        "Vending DragonKeep: Meds",
    "11866,2102":           "Vending WingedStorm: Guns",
    "12039,2104":           "Vending WingedStorm: Ammo",
    "11703,2101":           "Vending WingedStorm: Meds",
    "-702,8170":            "Vending Murderlin's Temple: Guns",
    "-688,8382":            "Vending Murderlin's Temple: Ammo",
    "-526,8541":            "Vending Murderlin's Temple: Meds",
    "-4411,27888":          "Vending HallowedHollow Entrance: Ammo",
    "-4321,27720":          "Vending HallowedHollow Entrance: Meds",
    "-4463,11658":          "Vending HallowedHollow Kingpin Approach: Meds",
    "-4521,11446":          "Vending HallowedHollow Kingpin Approach: Ammo",
    "11987,-10601":         "Vending GluttonyGulch Entrance: Guns",
    "11802,-10599":         "Vending GluttonyGulch Entrance: Ammo",
    "12170,-10603":         "Vending GluttonyGulch Entrance: Meds",
    "2370,-9019":           "Vending GluttonyGulch Kitchen: Ammo",
    "-5264,-21271":         "Vending GluttonyGulch Stabber Jabber: Guns",
    "-643,-5104":           "Vending GluttonyGulch Tribute Station: Guns",
    "-493,-5106":           "Vending GluttonyGulch Tribute Station: Meds",
    "-346,-5116":           "Vending GluttonyGulch Tribute Station: Ammo",
    "-22508,-6510":         "Vending MercenaryDay Entrance: Guns",
    "-22473,-6286":         "Vending MercenaryDay Entrance: Ammo",
    "-22290,-6099":         "Vending MercenaryDay Entrance: Meds",
    "579,-5489":            "Vending MercenaryDay Tinder Arena: Meds",
    "695,-5690":            "Vending MercenaryDay Tinder Arena: Ammo",
    "-28646,-18108":        "Vending Distillery Entrance: Meds",
    "-28810,-17913":        "Vending Distillery Entrance: Ammo",
    "3470,-7297":           "Vending Distillery Pot of Gold: Ammo",
    "-26015,-8933":         "Vending Distillery Wedding Venue: Meds",
    "-26327,-9001":         "Vending Distillery Wedding Venue: Ammo",
    "14366,10131":          "Vending WamBam Entrance: Ammo",
    "14206,10007":          "Vending WamBam Entrance: Meds",
    "7701,2177":            "Vending WamBam Water Wheel: Meds",
    "7576,2254":            "Vending WamBam Water Wheel: Ammo",
    "33637,15119":          "Vending WamBam Craw's Arena: Ammo",
    "33858,15043":          "Vending WamBam Craw's Arena: Meds",
    "-16947,66470":         "Vending Backburner Entrance: Ammo",
    "-16989,66902":         "Vending Backburner Entrance: Meds",
    "-26515,43992":         "Vending Backburner Vaughn's HQ: Guns",
    "-26266,44088":         "Vending Backburner Vaughn's HQ: Ammo",
    "-26389,44036":         "Vending Backburner Vaughn's HQ: Meds",
    "-21122,38254":         "Vending Backburner Marcus: Guns",
    "-21251,38221":         "Vending Backburner Marcus: Ammo",
    "-30491,37965":         "Vending DahlAbandon Entrance: Ammo",
    "-30584,37776":         "Vending DahlAbandon Entrance: Meds",
    "27315,27218":          "Vending DahlAbandon Mine Door: Ammo",
    "27224,27321":          "Vending DahlAbandon Mine Door: Meds",
    "40207,-3635":          "Vending Burrows Entrance: Ammo",
    "40076,-3749":          "Vending Burrows Entrance: Meds",
    "38103,-113737":        "Vending HeliosFallen Entrance: Ammo",
    "37976,-113661":        "Vending HeliosFallen Entrance: Meds",
    "32427,-100308":        "Vending HeliosFallen Munitions Loading: Ammo",
    "32293,-100304":        "Vending HeliosFallen Munitions Loading: Meds",
    "34348,-104837":        "Vending HeliosFallen The Arsenal: Ammo",
    "34172,-104726":        "Vending HeliosFallen The Arsenal: Meds",
    "-12483,723":           "Vending Mt.Scarab Entrance: Ammo",
    "-12345,748":           "Vending Mt.Scarab Entrance: Meds",
    "3050,-789":            "Vending Mt.Scarab Observation Deck: Ammo",
    "3055,-954":            "Vending Mt.Scarab Observation Deck: Meds",
    # "9910,-2559":         "Vending Paradise Sanctum Entrance: Ammo",
    # "9847,-2394":         "Vending Paradise Sanctum Entrance: Meds",
    # "11207,8546":         "Vending Paradise Sanctum Marcus Munitions: Guns",
    # "10569,6224":         "Vending Paradise Sanctum Marcus Munitions: Meds",
    # "4322,98":            "Vending Paradise Sanctum Hector: Ammo",
    # "4394,219":           "Vending Paradise Sanctum Hector: Meds",
    "9720,10034":           "Vending WrithingDeep: Ammo",
    "9899,10052":           "Vending WrithingDeep: Meds",
    "9099,10154":           "Vending Digistruct Spawn: Guns",
    "9279,10180":           "Vending Digistruct Spawn: Ammo",
    "9463,10175":           "Vending Digistruct Spawn: Meds",
    "-15300,27193":         "Vending DigistructInner Butcher Base: Ammo",
    # "4769,-3311":         "Vending DigistructInner Area of Anguish: Ammo",
    # "4242,-3312":         "Vending DigistructInner Area of Anguish: Meds",
    # "15713,13777":        "Vending DigistructInner Tower of Torment: Ammo",
}


enemy_class_to_loc_name = {
    "CharClass_PrimalBeast_KnuckleDragger":                                      "Enemy: Knuckle Dragger",
    "CharClass_PrimalBeast_Wamong":                                              "Enemy: Midgemong",
    "CharClass_BoomBoom":                                                        "Enemy: Boom",
    "CharClass_Boom":                                                            "Enemy: Bewm",
    "CharClass_Flynt":                                                           "Enemy: Captain Flynt",
    "CharClass_SavageLee":                                                       "Enemy: Savage Lee",
    "CharClass_Boll":                                                            "Enemy: Boll",
    "CharClass_MrMercy":                                                         "Enemy: Doc Mercy",
    "CharClass_Assassin2":                                                       "Enemy: Assassin Oney",
    "CharClass_Assassin1":                                                       "Enemy: Assassin Wot",
    "CharClass_Assassin3":                                                       "Enemy: Assassin Reeth",
    "CharClass_Assassin4":                                                       "Enemy: Assassin Rouf",
    "CharClass_SpiderantScorch":                                                 "Enemy: Scorch",
    "CharClass_IncineratorVanya_Combat":                                         "Enemy: Incinerator Clayton",
    "CharClass_Gettle":                                                          "Enemy: Gettle",
    "CharClass_Mobley":                                                          "Enemy: Mobley",
    "CharClass_BlackQueen":                                                      "Enemy: Black Queen",
    "CharClass_NomadNamed_1":                                                    "Enemy: Bad Maw",
    "CharClass_Prospector~Mad Mike":                                             "Enemy: Mad Mike",
    "CharClass_ConstructorRoland":                                               "Enemy: W4R-D3N",
    "CharClass_MonsterMash1":                                                    "Enemy: Spycho",
    "CharClass_McNally":                                                         "Enemy: McNally",
    "CharClass_MickZaford_Combat":                                               "Enemy: Mick/Tector",
    "CharClass_TectorHodunk_Combat":                                             "Enemy: Mick/Tector",
    "CharClass_Rat_Dan":                                                         "Enemy: Dan",
    "CharClass_Rat_Lee":                                                         "Enemy: Lee",
    "CharClass_Rat_Mick":                                                        "Enemy: Mick",
    "CharClass_Rat_Ralph":                                                       "Enemy: Ralph",
    "CharClass_RatEasterEgg":                                                    "Enemy: Flinter",
    "CharClass_Bugmorph_SirReginald":                                            "Enemy: Madame Von Bartlesby",
    "CharClass_Prospector~Prospector Zeke":                                      "Enemy: Prospector Zeke",
    "CharClass_Willhelm":                                                        "Enemy: Wilhelm",
    "CharClass_Laney":                                                           "Enemy: Laney White",
    "CharClass_RakkMan":                                                         "Enemy: Rakkman",
    "CharClass_BluntCrack":                                                      "Enemy: SmashHead",
    "CharClass_Midget_SwallowedWhole":                                           "Enemy: Shorty",
    "CharClass_Stalker_SwallowedWhole":                                          "Enemy: Sinkhole",
    "CharClass_RatMidget~Bloody":                                                "Enemy: Bloody",
    "CharClass_RatMidget~Crabby":                                                "Enemy: Crabby",
    "CharClass_RatMidget~Creepy":                                                "Enemy: Creepy",
    "CharClass_RatMidget~Dirty":                                                 "Enemy: Dirty",
    "CharClass_RatMidget~Greedy":                                                "Enemy: Greedy",
    "CharClass_RatMidget~Sleazy":                                                "Enemy: Sleazy",
    "CharClass_RatMidget~Tipsy":                                                 "Enemy: Tipsy",
    "CharClass_ThresherSlappy":                                                  "Enemy: Old Slappy",
    "CharClass_ThresherGluttonous":                                              "Enemy: Gluttonous Thresher",
    "CharClass_Stalker_Name1":                                                   "Enemy: Henry",
    "CharClass_Leprechaun":                                                      "Enemy: Bagman",
    "CharClass_SafeCrystalisk~Blue":                                             "Enemy: Blue",
    "CharClass_CreeperBadass":                                                   "Enemy: Badass Creeper",
    "CharClass_SkagPair":                                                        "Enemy: Tumbaa",
    "CharClass_StalkerPair":                                                     "Enemy: Pimon",
    "CharClass_NamedRakk1":                                                      "Enemy: Son of Mothrakk",
    # "GD_BloodwingNew.Character.CharClass_Bloodwing":                           "Enemy: Bloodwing",
    "CharClass_Goliath~Fatal GOD-liath":                                         "Enemy: GOD-liath",
    "CharClass_GoliathTurret~GOD-liath":                                         "Enemy: GOD-liath",
    "CharClass_GoliathBlaster~GOD-liath Blaster":                                "Enemy: GOD-liath",
    "CharClass_GoliathCorrosive~Caustic GOD-liath":                              "Enemy: GOD-liath",
    "CharClass_GoliathLootGoon~GOD-liath Goon":                                  "Enemy: GOD-liath",
    "CharClass_ProspectorGoliath~GOD-liath Digger":                              "Enemy: GOD-liath",
    "CharClass_LootMidget_Goliath~Loot Midget GOD-liath":                        "Enemy: GOD-liath",
    "CharClass_ArenaGoliath~GOD-liath Gladiator":                                "Enemy: GOD-liath",
    "CharClass_Allium_GoliathSnow~Fatal Snow GOD-liath":                         "Enemy: GOD-liath",
    "CharClass_Anemone_Infected_Goliath~Infected GOD-liath":                     "Enemy: GOD-liath",
    "CharClass_Anemone_Infected_Goliath~Decaying GOD-liath":                     "Enemy: GOD-liath",
    "CharClass_Anemone_Infected_Badass_Goliath~Badass GOD-liath":                "Enemy: GOD-liath",
    "CharClass_Anemone_Infected_Badass_Goliath~Badass Decaying GOD-liath":       "Enemy: GOD-liath",
    "CharClass_Anemone_Gargantuan_Goliath~Badass GOD-liath":                     "Enemy: GOD-liath",
    "CharClass_Anemone_Gargantuan_Goliath~Badass Decaying GOD-liath":            "Enemy: GOD-liath",
    "CharClass_SarcasticSlab":                                                   "Enemy: Sarcastic Slab",
    "CharClass_Skagzilla":                                                       "Enemy: Dukino's Mom",
    "CharClass_MadDog":                                                          "Enemy: Mad Dog",
    "CharClass_Sheriff":                                                         "Enemy: Sheriff Nisha",
    "CharClass_Deputy":                                                          "Enemy: Deputy Winger",
    "CharClass_Engineer_Foreman":                                                "Enemy: Foreman Jasper",
    "CharClass_JacksBodyDouble":                                                 "Enemy: Jack's Body Double",
    # "" :                                                                       "Enemy: BNK-3R",
    "CharClass_PrimalBeast_KONG":                                                "Enemy: King Mong",
    "CharClass_PrimalBeast_DonkeyMong":                                          "Enemy: Donkey Mong",
    "CharClass_Mortar":                                                          "Enemy: Mortar",
    "CharClass_Engineer_DJHyperion":                                             "Enemy: Hunter Hellquist",
    "CharClass_BoneHead2":                                                       "Enemy: Bone Head 2.0",
    "CharClass_LoaderUltimateBadass~Saturn":                                     "Enemy: Saturn",
    # "" :                                                                       "Enemy: Warrior",
    "CharClass_Thresher_Raid":                                                   "Enemy: Terramorphous the Invincible",

    "CharClass_Spycho":                                                          "Enemy: Sully the Blacksmith",
    "CharClass_PumpkinheadFlying":                                               "Enemy: Pumpkin Kingpin",
    "CharClass_UndeadFirePsycho_Giant":                                          "Enemy: Cryptkeeper Clark",
    "CharClass_ButcherBoss":                                                     "Enemy: Chef Gouda Ramsay",
    "CharClass_RatChef":                                                         "Enemy: The Rat in the Hat",
    "CharClass_ButcherBoss2":                                                    "Enemy: Chef Brulee",
    "CharClass_ButcherBoss3":                                                    "Enemy: Chef Bork Bork",
    "CharClass_BigBird":                                                         "Enemy: Wattle Gobbler",
    "CharClass_SandMale":                                                        "Enemy: Glasspool, Tribute of Wurmwater",
    "CharClass_SandFemale":                                                      "Enemy: William, Tribute of Wurmwater",
    "CharClass_EngineerMale":                                                    "Enemy: Axel, Tribute of Opportunity",
    "CharClass_EngineeFemale":                                                   "Enemy: Rose, Tribute of Opportunity",
    "CharClass_FleshripperFemale":                                               "Enemy: Strip, Tribute of Southern Shelf",
    "CharClass_FleshripperMale":                                                 "Enemy: Flay, Tribute of Southern Shelf",
    "CharClass_CraterFemale":                                                    "Enemy: Bailly, Tribute of Sawtooth Cauldron",
    "CharClass_CraterMale":                                                      "Enemy: Moretus, Tribute of Sawtooth Cauldron",
    "CharClass_IncineratorFemale":                                               "Enemy: Cynder, Tribute of Frostburn",
    "CharClass_IncineratorMale":                                                 "Enemy: Fuse, Tribute of Frostburn",
    "CharClass_Lynchwood_Female":                                                "Enemy: Annie, Tribute of Lynchwood",
    "CharClass_Lynchwood_Male":                                                  "Enemy: Garret, Tribute of Lynchwood",
    "CharClass_RaiderFemale":                                                    "Enemy: Fiona, Tribute of Sanctuary",
    "CharClass_RaiderMale":                                                      "Enemy: Max, Tribute of Sanctuary",
    "CharClass_Snowman":                                                         "Enemy: Tinder Snowflake",
    "CharClass_GoliathGroom":                                                    "Enemy: Colin Zaford",
    "CharClass_GoliathBride":                                                    "Enemy: Bridget Hodunk",
    "CharClass_BlingLoader":                                                     "Enemy: BLNG Loader",
    "CharClass_Nast_Girl_Loader":                                                "Enemy: Stella",
    "CharClass_Nast_BadassJunkLoader":                                           "Enemy: Ed",
    "CharClass_Innuendobot_NPC":                                                 "Enemy: Innuendobot 5000",
    "CharClass_Nast_ThresherSigmund":                                            "Enemy: Sigmand",
    "CharClass_Nast_ThresherIkaroa":                                             "Enemy: Ikaroa",
    "CharClass_Nast_ThresherMoby":                                               "Enemy: Moby",
    "CharClass_ThresherBadassFire~Fire Crak'n":                                  "Enemy: Fire Crak'n",
    "CharClass_Nast_ThresherLove":                                               "Enemy: Rue, the Love Thresher",
    "CharClass_Crawmerax_Son~Son of Crawmerax the Invincible":                   "Enemy: Son of Crawmerax",
    "CharClass_Crawmerax_Son~The Invincible Son of Crawmerax the Invincible":    "Enemy: Son of Crawmerax Raid Boss",
    "CharClass_FlyntSon":                                                        "Enemy: Sparky Flynt",
    "CharClass_Orchid_Pirate_NoBeard":                                           "Enemy: No Beard",
    "CharClass_Orchid_StalkerPet":                                               "Enemy: Tinkles",
    "CharClass_Orchid_Grendel":                                                  "Enemy: Grendel",
    "CharClass_Orchid_MarauderMaster":                                           "Enemy: Sandman",
    "CharClass_Orchid_BigSleep":                                                 "Enemy: Big Sleep",
    "CharClass_Orchid_Deserter_Cook":                                            "Enemy: Benny the Booster",
    "CharClass_Orchid_Deserter_Deckhand":                                        "Enemy: Deckhand",
    "CharClass_Orchid_Deserter_Terry":                                           "Enemy: Toothless Terry",
    "CharClass_Orchid_Pervbot":                                                  "Enemy: P3RV-E",
    "CharClass_Orchid_LoaderBoss":                                               "Enemy: H3RL-E",
    "CharClass_Orchid_PirateRadioGuy":                                           "Enemy: DJ Tanner",
    "CharClass_Orchid_MrBubbles":                                                "Enemy: Mr. Bubbles",
    "CharClass_Orchid_Pirate Henchman2":                                         "Enemy: Lieutenant Hoffman (Pirate)",
    "CharClass_Orchid_PirateHenchman":                                           "Enemy: Lieutenant White (Pirate)",
    "CharacterClass_RakkHive":                                                   "Enemy: Roscoe",
    "CharClass_Orchid_BossWorm":                                                 "Enemy: The Leviathan",
    "CharClass_Orchid_RaidEngineer":                                             "Enemy: Hyperius",
    "CharClass_Orchid_RaidShaman":                                               "Enemy: Master Gee",
    "CharClass_Iris_Pyro_Pete":                                                  "Enemy: Pyro Pete",
    "CharClass_Iris_SullyStabber":                                               "Enemy: Sully the Stabber",
    "CharClass_Iris_Hamhock":                                                    "Enemy: Hamhock",
    "CharClass_Iris_BuffGamer":                                                  "Enemy: Buff Gamer",
    "CharClass_Iris_GameCritic":                                                 "Enemy: Game Critic",
    "CharClass_Iris_MotorMama":                                                  "Enemy: Motor Mama",
    "CharClass_Iris_SayFaceTroll":                                               "Enemy: Anonymous Troll",
    "CharClass_Iris_Uriah":                                                      "Enemy: Uriah",
    "CharClass_Iris_BlimpBoss":                                                  "Enemy: Piston's Blimp",
    "CharClass_Truckasaurus":                                                    "Enemy: Badassasaurus",
    "CharClass_Iris_Piston_Boss":                                                "Enemy: Piston",
    "CharClass_Iris_Raid_PyroPete":                                              "Enemy: Pyro Pete the Invincible",
    "CharClass_DrifterNamed":                                                    "Enemy: Arizona",
    "CharClass_Sage_Ep3_Creature":                                               "Enemy: Thermitage",
    "CharClass_Sage_DahliaMurder_Creature":                                      "Enemy: Rakkanoth",
    "CharClass_Sage_FollowGlow_Creature":                                        "Enemy: Dribbles",
    "CharClass_Sage_Ep4_Creature":                                               "Enemy: Woundspike",
    "CharClass_Sage_PallingAround_Creature":                                     "Enemy: The Bulwark",
    "CharClass_Sage_BigFeet_Creature":                                           "Enemy: Rouge",
    "CharClass_Sage_NowYouSeeIt":                                                "Enemy: Bloodtail",
    "CharClass_Sage_FinalBoss":                                                  "Enemy: Jackenstein",
    "CharClass_Sage_DrNakayama":                                                 "Enemy: Dr. Nakayama",
    "CharClass_Sage_AcquiredTaste_Creature":                                     "Enemy: Bulstoss",
    "CharClass_BoneyPants":                                                      "Enemy: Mr. Boney Pants Guy",
    "CharClass_Golem_SwordInStone":                                              "Enemy: Unmotivated Golem",
    "CharClass_SirReginald":                                                     "Enemy: Sir Reginald von Bartlesby",
    "CharClass_Spiderpants":                                                     "Enemy: Spiderpants",
    "CharClass_Orc_Butcher":                                                     "Enemy: Arguk the Butcher",
    "CharClass_Orc_WarlordNamed2":                                               "Enemy: Warlord Glug",
    "CharClass_Knight_LostSoulsInv_Proto2":                                      "Enemy: -=n00bkiller=-",
    "CharClass_Knight_MMO1_Proto":                                               "Enemy: 420_E-Sports_Masta",
    "CharClass_Knight_MMO2_Proto":                                               "Enemy: [720NoScope]Headshotz",
    "CharClass_Knight_MMO3_Proto":                                               "Enemy: xxDatVaultHuntrxx",
    "CharClass_Skeleton_King~King Aliah":                                        "Enemy: King Aliah",
    "CharClass_Skeleton_King~King Crono":                                        "Enemy: King Crono",
    "CharClass_Skeleton_King~King Seth":                                         "Enemy: King Seth",
    "CharClass_Skeleton_King~King Nazar":                                        "Enemy: King Nazar",
    "CharClass_FlyingGolem~Maxibillion":                                         "Enemy: Maxibillion",
    "CharClass_Orc_ClaptrapWand":                                                "Enemy: Magical Orc",
    "CharClass_Spider_ClaptrapWand":                                             "Enemy: Magical Spider",
    "CharClass_Greedtooth":                                                      "Enemy: Greedtooth",
    "CharClass_WinterKnight_Canine":                                             "Enemy: Canine",
    "CharClass_WinterKnight_Molehill":                                           "Enemy: Molehill",
    "CharClass_SirBoil":                                                         "Enemy: Sir Boil",
    "CharClass_SirMash":                                                         "Enemy: Sir Mash",
    "CharClass_SirStew":                                                         "Enemy: Sir Stew",
    "CharClass_DragonBridgeBoss":                                                "Enemy: Handsome Dragon",
    "CharClass_AngelBoss":                                                       "Enemy: Sorcerer's Daughter",
    "CharClass_Wizard_DeadBrotherEdgar_Proto2":                                  "Enemy: Edgar/Simon",
    "CharClass_Wizard_DeadBrotherSimon_Proto2":                                  "Enemy: Edgar/Simon",
    "CharClass_JackWarlock~Demonic Sorcerer":                                    "Enemy: Handsome Sorcerer",
    "CharClass_DragonRed_Raid":                                                  "Enemy: Incinerator",
    "CharClass_DragonBlue_Raid":                                                 "Enemy: Healianth",
    "CharClass_DragonGreen_Raid":                                                "Enemy: Brood",
    "CharClass_DragonPurple_Raid":                                               "Enemy: Boost",
    "CharClass_Orc_WarlordNamed3":                                               "Enemy: Warlord Turge",
    "CharClass_Orc_WarlordNamed1":                                               "Enemy: Warlord Slog",
    "CharClass_Anemone_Skag_Ghost":                                              "Enemy: Ghost",
    "CharClass_Anemone_TheDarkWeb":                                              "Enemy: The Dark Web",
    "CharClass_Anemone_UranusBOT":                                               "Enemy: Uranus Bot",
    "CharClass_Anemone_Lt_Angvar":                                               "Enemy: Lt. Angvar (New Pandora)",
    "CharClass_Anemone_Lt_Bolson":                                               "Enemy: Lt. Bolson (New Pandora)",
    "CharClass_Anemone_Lt_Tetra":                                                "Enemy: Lt. Tetra (New Pandora)",
    "CharClass_Anemone_Lt_Hoffman":                                              "Enemy: Lt. Hoffman (New Pandora)",
    "CharClass_Anemone_Cassius":                                                 "Enemy: Cassius",
    "CharClass_Anemone_Hector":                                                  "Enemy: Hector",
    "CharClass_DrifterRaid":                                                     "Enemy: Dexiduous the Invincible",
    "CharClass_Native_Badass~Omnd-Omnd-Ohk":                                     "Enemy: Omnd-Omnd-Ohk",
    "CharClass_Nast_Native_Badass~Omnd-Omnd-Ohk":                                "Enemy: Omnd-Omnd-Ohk",
    "CharClass_Sage_Raid_Beastmaster":                                           "Enemy: Chief Ngwatu",
    "CharClass_Sage_Raid_Beast":                                                 "Enemy: Voracidous the Invincible",
    "CharacterClass_Anemone_SandWormBoss_1":                                     "Enemy: Haderax the Invincible",
    "CharClass_BugMorphRaid":                                                    "Enemy: Vermivorous the Invincible",
}
